{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职之家 - 管理中心{% endblock %}

{% block content %}
<style type="text/css">
	
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">管理中心</h1>
</header>

<div class="mui-content">
	<div id="usertop">
		<div class="userinfo clearfix">
			<div class="userimg left">
				<img src="{{ data['userinfo']['headimgurl'] }}" class="auto-center">
			</div>
			<div class="info">
				<div class="name">{{ data['userinfo']['nickname'] }}</div>
				<div class="else"><span class="score">4.9</span>52单</div>
			</div>
			<button id="Sign">签到</button>
		</div>
		
	</div>
	<div class="container">
		<ul class="mui-table-view mylink">
			<li class="mui-table-view-cell">
				<a href="/manager/info" class="mui-navigate-right">
					<span class="ident3"></span>个人信息
				</a>
			</li>
			<li class="mui-table-view-cell none">
				<a href="/job/purse" class="mui-navigate-right">
					<span class="ident1"></span>我的钱包
				</a>
			</li>
			<li class="mui-table-view-cell none">
				<a href="/manager/signlist" class="mui-navigate-right">
					<span class="ident5"></span>报名管理
				</a>
			</li>
			<li class="mui-table-view-cell">
				<a href="/manager/index" class="mui-navigate-right">
					<span class="ident4"></span>岗位管理
				</a>
			</li>
			<li class="mui-table-view-cell">
				<a href="javascript:void(0)" class="mui-navigate-right" id="checkphone">
					<span class="ident3"></span>发布岗位
				</a>
			</li>
			
		</ul>
		<br>
		<ul class="mui-table-view mylink">
			<li class="mui-table-view-cell none">
				<a href="/job/resume" class="mui-navigate-right">
					<span class="ident2"></span>我的简历
				</a>
			</li>
			<li class="mui-table-view-cell none">
				<a href="#" class="mui-navigate-right">
					<span class="ident3"></span>我的收藏
				</a>
			</li>
			<li class="mui-table-view-cell none">
				<a href="#" class="mui-navigate-right">
					<span class="ident4"></span>邀请有奖
				</a>
			</li>
			<li class="mui-table-view-cell none">
				<a href="#" class="mui-navigate-right">
					<span class="ident5"></span>意见反馈
				</a>
			</li>
			<li class="mui-table-view-cell">
				<a href="/job/aboutus" class="mui-navigate-right">
					<span class="ident6"></span>关于我们
				</a>
			</li>
			<li class="mui-table-view-cell">
				<a href="/manager/setting" class="mui-navigate-right">
					<span class="ident7"></span>账号设置
				</a>
			</li>
		</ul>
	</div>
	<br>
	<br>
</div>

<script type="text/javascript">

	$("#checkphone").on('tap',function(){
		$.get('/manager/checkphone',function(data){
			if(data.error_code == '0'){
				window.location.href = '/manager/release';
			} else {
				var btnArray = ['取消', '去验证'];
				mui.confirm("发布岗位需要先绑定个人信息", '请完善个人信息', btnArray, function(e) {
					if (e.index == 1) {
						window.location.href = '/manager/info';
					} else {
						
					}
				})
			}
		},'json');
	})
</script>
{% endblock %}
{% block footer %}
       
{% endblock %}