{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 岗位管理{% endblock %}

{% block content %}
<style type="text/css">
	body,html{
		background: #fafafa;
	}
	.mui-content {
		background: #fafafa;
	}
	
</style>

<header class="mui-bar mui-bar-nav">
	<!-- <a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a> -->
	<h1 class="mui-title">岗位管理</h1>
	<a class="mui-pull-right" href="/manager/admin"><span class="mui-icon mui-icon-contact"></span></a>
</header>

<div class="mui-content">
	<a href="http://www.jobchain.us/db/index" id="ManagerBanner"></a>
	<p id="checkphone" class="none">首次发布岗位需要实名认证<a href="/manager/info">去认证 > </a></p>
	<div class="container" style="padding:15px;">
		{%if data['job']%}
			{% for key, item in data['job'] %}
				<div class="works" idvalue = "{{ item['id'] }}">
					<!--<span class="status statA">审核中</span>
					<span class="status statB">审核通过</span>
					<span class="status statC">审核拒绝</span>-->
					<span class="status statB">审核通过</span>
					<h3>{{ item['title'] }}</h3>
					<div class="row people">
						<div class="col-xs-4">
							<a href="/manager/signlist?jobid={{ item['id'] }}">
								<p class="num">{{ item['applynum'] }}</p>
								<p class="tit">报名人数</p>
							</a>
						</div>
						<div class="col-xs-4">
							<a href="/manager/signlist?jobid={{ item['id'] }}">
								<p class="num">{{ item['applyYnum'] }}</p>
								<p class="tit">录取人数</p>
							</a>
						</div>
						<div class="col-xs-4">
							<p class="num">{{ item['view_num'] }}</p>
							<p class="tit">浏览人数</p>
						</div>
					</div>
					<div class="row control">
						<div class="col-xs-3 none">
							<a href="javascript:void(0)" class="share">分享</a>
						</div>
						<div class="col-xs-3 none">
							<a href="javascript:void(0)" class="extend">全网推</a>
						</div>
						<div class="col-xs-3 right">
							<a href="javascript:void(0)" class="delete" data-id="{{ item['id'] }}">删除</a>
						</div>
						<div class="col-xs-3 right">
							<a href="/manager/release?jobid={{ item['id'] }}" class="modify">修改</a>
						</div>
						<div class="col-xs-3 right">
							<a href="/job/detail?jobid={{ item['id'] }}" class="share">查看</a>
						</div>
					</div>
				</div>
			{% endfor %}
		{% else %}
			<div class='noneshow'>您尚未发布工作。<a href="javascript:void(0)" class="tips checkphone">去发布</a></div>
		{% endif %}
	</div>
</div>

<script type="text/javascript">

	$(function(){
		$.get('/manager/checkphone',function(data){
			if(data.error_code != '0'){
				$("#checkphone").show();
			} else {

			}
		},'json');
	})

	$(".control .delete").on('tap',function(){
		var dom = $(this).parents('.works');
		var id = $(this).attr('data-id');
		var btnArray = ['取消', '删除'];
		mui.confirm("您确定要删除该岗位？", '删除岗位', btnArray, function(e) {
			if (e.index == 1) {
				$.get('/manager/deljob',{'jobid':id},function(data){
					if(data.error_code == '0'){
						layer.msg("删除成功。");
						dom.remove();
					} else {
						layer.msg(data.reason);
					}
				},'json');
			} else {
				
			}
		})
	});

	$(".checkphone").on('tap',function(){
		$.get('/manager/checkphone',function(data){
			if(data.error_code == '0'){
				window.location.href = '/manager/release';
			} else {
				var btnArray = ['取消', '去验证'];
				mui.confirm("发布岗位需要先绑定个人信息", '请完善个人信息', btnArray, function(e) {
					if (e.index == 1) {
						window.location.href = '/manager/info';
					} else {
						
					}
				})
			}
		},'json');
	})

</script>
{% endblock %}
{% block footer %}
       
{% endblock %}