{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职之家 - 个人信息{% endblock %}

{% block content %}
<style type="text/css">
	.imgbox {
	    margin: 0 auto;
	    margin-top: 10px;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">个人信息</h1>
</header>

<div class="mui-content">
	<div class="resu boxcontain container" id="ManagerBind">
		<div class="mui-input-row">
			<label>真实姓名</label>
			<input type="text" placeholder="请输入您的真实姓名" value="{{ data['userinfo']['real_name'] }}" id="username">
		</div>
		<div class="mui-input-row">
			<label>企业名称</label>
			<input type="text" placeholder="请输入您的企业名称" value="{{ data['userinfo']['company_name'] }}" id="companyname">
		</div>
		<div class="mui-input-row">
			<label>手机号</label>
			<input type="text" placeholder="请输入您的手机号" value="{{ data['userinfo']['phone'] }}" id="telphone">
		</div>
		<div class="mui-input-row">
			<input type="number" name="captcha" placeholder="请输入短信验证码" id="captcha">
			<button class="getcaptcha">获取验证码</button>
			<button class="waiting none"></button>
		</div>
		<div class="mar10">
			<label>微信二维码</label>
			<span class="btn btn-default fileinput-button">
	            <span>上传图片...</span>
	            <input type="file" accept="image/jpg ,image/jpeg ,image/png" onchange="imgChange(event)" id="file">
	        </span>
	        <div class="imgbox rel">
				<img src="{{ data['userinfo']['wxcode_img'] }}" class="auto-center" id="showImage">
			</div>
		</div>
	</div>
	<button class="footbtn" id="TelBind">绑定</button>
</div>

<script type="text/javascript">

	var base;

	function imgChange(e) {
	    var reader = new FileReader();
	    reader.onload = (function (file) {
	        return function (e) {
	        	if(e.total>10*1024*1024){
			        //alert('上传的图片的大于4M,请重新选择');
			        layer.msg('上传的图片的大于10M,请重新选择。',{icon: 5});
			        return false;
		        } else {
		        	$('.imgbox').css({"width":"8rem","height":"8rem"});
		        	var IMG = new Image();
		        	IMG.src = this.result;
		            IMG.onload = function(){
	      				var w = this.naturalWidth, h = this.naturalHeight , resizeW = 0, resizeH = 0;
	      				console.log(w,h)
	      			
		      			var maxSize = {
					        width: 1200,
					        height: 1000,
					        level: 0.6
					    };
					    if(w > maxSize.width || h > maxSize.height){
					        var multiple = Math.max(w / maxSize.width, h / maxSize.height);
					        resizeW = w / multiple;
					        resizeH = h / multiple;
					        var canvas = document.createElement('canvas'),
						    ctx = canvas.getContext('2d');
					        canvas.width = resizeW;
					        canvas.height = resizeH;
					        ctx.drawImage(IMG, 0, 0, resizeW, resizeH);
						    var base64 = canvas.toDataURL('image/jpeg', maxSize.level);
						    $("#showImage")[0].src=base64;
				            base = base64
				            console.log(base)
					    } else {
					        // 如果图片尺寸小于最大限制，则不压缩直接上传
					        $("#showImage")[0].src=IMG.src;
				            //var arr = IMG.src.split(',');
				            base = IMG.src;
				            console.log(base);
					    }
					    
				    }
	        	
	            //console.log(this.result); //这个就是base64的数据了
		            // $("#showImage")[0].src=this.result;
		            // var arr = this.result.split(',');
		            // base = arr[1];
		            // console.log(base);
	            }
	        };
	    })(e.target.files[0]);
	    reader.readAsDataURL(e.target.files[0]);
	}

	$('.getcaptcha').on('tap',function(){
		var mobile = $("#telphone").val();
		if(mobile.length == ''){
	        layer.msg('请填写手机号。');
	        return false;
	    }
		if(mobile.length != 11){
	        layer.msg('手机号长度不正确。');
	        return false;
	    }
	    if(!checkMobile(mobile)){
	    	layer.msg('请输入正确的手机号。');
        	return false;
        }

        $(this).attr('disabled','disabled');
        $.get('/manager/getphonecode',{'mobile':mobile},function(data){
			if(data.error_code == '0'){
				mobileMsg();
			} else {
				layer.msg(data.reason);
			}
		},'json');
	});

	$("#TelBind").on('tap',function(){
		var real_name = $("#username").val();
		if(real_name.length == ''){
	        layer.msg('请填写姓名。');
	        return false;
	    }
	    if(!checkName(real_name)){
	    	layer.msg('请填写真实姓名。');
        	return false;
        }

        var company_name = $("#companyname").val();
        if(company_name.length == ''){
	        layer.msg('请填写企业名称。');
	        return false;
	    }

        var mobile = $("#telphone").val();
		if(mobile.length == ''){
	        layer.msg('请填写手机号。');
	        return false;
	    }
		if(mobile.length != 11){
	        layer.msg('手机号长度不正确。');
	        return false;
	    }
	    if(!checkMobile(mobile)){
	    	layer.msg('请输入正确的手机号。');
        	return false;
        }

	    var vcode = $("#captcha").val();
	    if(vcode.length == ''){
	        layer.msg('请填写短信验证码。');
	        return false;
	    }

	    if(!base || base == ''){
	    	layer.msg('请上传微信二维码。');
	        return false;
	    }

	    $.post('/manager/edituserinfo',{
	    	'mobile':mobile,
	    	'vcode':vcode,
	    	'real_name':real_name,
	    	'company_name':company_name,
	    	'base64':base
	    },function(data){
			if(data.error_code == '0'){
				mui.alert('您已完成个人信息绑定', '绑定成功！',function(){
					window.location.href = "/manager/admin";
				});
			} else {
				layer.msg(data.reason);
			}
		},'json');
	})

</script>
{% endblock %}
{% block footer %}
       
{% endblock %}