{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 信息中心{% endblock %}

{% block content %}
<style type="text/css">
	html,body {
		height: 100%;
		background-color: #efeff4;
	}
	.mui-bar-nav~.mui-content {
		padding-bottom: 5.82rem;
	}
	h2 {
		margin:0;
		margin-top:10px;
		margin-bottom: 5px;
		color:#c6cacf;
		font-size:1rem;
		text-align: center;
	}
	.mui-card h4 {
		color:#f17b28;
		font-size:1.8rem;
	}
	.mui-card p {
		color:#000;
		font-size:1.2rem;
	}
	.mui-card-footer a {
		display: block;
		width: 100%;
		text-align: center;
		font-size:1.4rem;
		color:#f17b28;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">信息中心</h1>
	<a class="mui-pull-right" href="/manager/admin"><span class="mui-icon mui-icon-contact"></span></a>
</header>

{% if data['sysnotice'] %}
<div class="mui-content">
	{% for key, item in data['sysnotice'] %}
	<h2>{{  item['create_time'] }}</h2>
	<div class="mui-card">
		<div class="mui-card-content">
			<div class="mui-card-content-inner">
				{% if item['type'] == 'applyjob' %}
				<h4>求职申请通知</h4>
				{% elseif item['type'] == 'getjob' %}
				<h4>求职录取通知</h4>
				{% else %}
				<h4>其它</h4>
				{% endif %}
				<p>{{item['content']}}</p>
			</div>
		</div>
		<div class="mui-card-footer">
			<a href="{{ item['url'] }}" class="link">查看详情</a>
		</div>
	</div>
	{% endfor %}
</div>
{% else %}
<div class="mui-content">
	<img src="/public/img/message.png" class="nomessage">
	<div class="noneshow">
		暂无系统消息
	</div>
</div>
{% endif %}

{% endblock %}
{% block footer %}
       
{% endblock %}