{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职之家 - 发布岗位{% endblock %}

{% block content %}
<style type="text/css">
	body,html {
		background: #fff;
	}
	.statbox img.auto-center {
		max-width: 90%;
	}
	.resu {
		padding:0;
	}
	
	.imgbox {
	    margin: 0 auto;
	    margin-top: 10px;
	}
	.col-xs-6 button {
		display: block;
		width: 100%;
	    height: 3rem;
	    line-height: 2rem;
	    background: #f07527;
	    color: #fff;
	    font-size: 1.8rem;
	    text-align: center;
	    border-radius: 3rem;
	    margin: 0 auto;
	    margin-top: 2rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">发布岗位</h1>
</header>

<div class="mui-content">
	<div class="release boxcontain container" id="RelA" data-rid="1">
		<h2>发布兼职 (1)</h2>
		<div class="statbox">
			<img src="/public/img/relA.png" class="auto-center">
		</div>
		<div class="boxcontain mar10 resu">
			<div class="mui-input-row">
				<label>岗位类别</label>
				<input type="text" placeholder="请选择岗位类别" id="jobtype" value="">
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6 right">
				<button class="turn" data-turn="2">下一步</button>
			</div>
		</div>
	</div>
	<div class="release boxcontain container none" id="RelB" data-rid="2">
		<h2>发布兼职 (2)</h2>
		<div class="statbox">
			<img src="/public/img/relB.png" class="auto-center">
		</div>
		<div class="boxcontain mar10">
			<input type="text" placeholder="请输入职位名称" id="jobname" value="">
			<pre class="texts hidepre" id="pre"></pre>
			<textarea class="texts" id="textarea" placeholder="请输入职位描述"></textarea>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<button class="turn" data-turn="1">上一步</button>
			</div>
			<div class="col-xs-6">
				<button class="turn" data-turn="3">下一步</button>
			</div>
		</div>
	</div>
	<div class="release boxcontain container none" id="RelC" data-rid="3">
		<h2>发布兼职 (3)</h2>
		<div class="statbox">
			<img src="/public/img/relC.png" class="auto-center">
		</div>
		<div class="boxcontain mar10 resu">
			<div class="mui-input-row">
				<label>计薪方式</label>
				<input type="text" placeholder="请选择计薪方式" id="paytype" value="">
			</div>
			<div class="mui-input-row">
				<label>薪资</label>
				<input type="text" placeholder="请输入金额(元)" id="paymoney" value="">
			</div>
			<div class="mui-input-row">
				<label>结算时间</label>
				<input type="text" placeholder="请选择结算时间" id="paytime" value="">
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<button class="turn" data-turn="2">上一步</button>
			</div>
			<div class="col-xs-6">
				<button class="turn" data-turn="4">下一步</button>
			</div>
		</div>
	</div>
	<div class="release boxcontain container none" id="RelD" data-rid="4">
		<h2>发布兼职 (4)</h2>
		<div class="statbox">
			<img src="/public/img/relD.png" class="auto-center">
		</div>
		<div class="boxcontain mar10 resu">
			<div class="mui-input-row">
				<label>开始日期</label>
				<input type="text" placeholder="请选择开始日期" id="jobstarday" value="" data-options='{"type":"date","beginYear":2018,"endYear":2022}'>
			</div>
			<div class="mui-input-row">
				<label>结束日期</label>
				<input type="text" placeholder="请选择结束日期" id="jobendday" value="" data-options='{"type":"date","beginYear":2018,"endYear":2022}'>
			</div>
			<div class="mui-input-row">
				<label>开始时间</label>
				<input type="text" placeholder="请选择开始时间" id="jobstartime" value="" data-options='{"type":"time"}'>
			</div>
			<div class="mui-input-row">
				<label>结束时间</label>
				<input type="text" placeholder="请选择结束时间" id="jobendtime" value="" data-options='{"type":"time"}'>
			</div>
			<div class="mui-input-row">
				<label>工作地点</label>
				<!-- <span class="btn btn-default fileinput-button">
		            <span>上传图片...</span>
		            <input type="button" id="addaddress">
		        </span> -->
				<input type="text" placeholder="添加工作地点" id="inputAddress" v-model="inputtext">
				
			</div>
			<!-- <div id="r-result"></div> -->
		</div>
		<div class="row">
			<div class="col-xs-6">
				<button class="turn" data-turn="3">上一步</button>
			</div>
			<div class="col-xs-6">
				<button class="turn" data-turn="5">下一步</button>
			</div>
		</div>
	</div>
	<div class="release boxcontain container none" id="RelE" data-rid="5">
		<h2>发布兼职 (5)</h2>
		<div class="statbox">
			<img src="/public/img/relE.png" class="auto-center">
		</div>
		<div class="boxcontain mar10 resu">
			<div class="mui-input-row">
				<label>企业全称</label>
				<input type="text" placeholder="请输入企业全称" id="companyname" value="">
			</div>
			<div class="mui-input-row">
				<label>联系人</label>
				<input type="text" placeholder="请输入联系人姓名" id="companyman" value="">
			</div>
			<div class="mui-input-row">
				<label>联系电话</label>
				<input type="text" placeholder="请输入联系电话" id="companytel" value="">
			</div>
			<div class="mar10">
				<label>微信二维码</label>
				<span class="btn btn-default fileinput-button">
		            <span>上传图片...</span>
		            <input type="file" accept="image/jpg ,image/jpeg ,image/png" onchange="imgChange(event)" id="file">
		        </span>
		        <div class="imgbox rel">
					<img src="" class="auto-center" id="showImage">
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<button class="turn" data-turn="4">上一步</button>
			</div>
			<div class="col-xs-6">
				<button class="push">发布</button>
			</div>
		</div>
	</div>
</div>

<!-- <div id="Address" class="boxcontain container">
	<input type="text" placeholder="请输入地址" id="addressText" value="">
	
</div> -->

<div id="allmap"></div>
<script type="text/javascript">

	var indexAddress;

	var textarea = document.getElementById('textarea');
	var pre = document.getElementById('pre');

	textarea.oninput = function() {
	    pre.textContent = textarea.value;
	    textarea.style.height = pre.offsetHeight + 'px';
	}

	var base;

	function imgChange(e) {
	    var reader = new FileReader();
	    reader.onload = (function (file) {
	        return function (e) {
	        	if(e.total>10*1024*1024){
			        //alert('上传的图片的大于4M,请重新选择');
			        layer.msg('上传的图片的大于10M,请重新选择。',{icon: 5});
			        return false;
		        } else {
		        	$('.imgbox').css({"width":"8rem","height":"8rem"});
		        	var IMG = new Image();
		        	IMG.src = this.result;
		            IMG.onload = function(){
	      				var w = this.naturalWidth, h = this.naturalHeight , resizeW = 0, resizeH = 0;
	      				console.log(w,h)
	      			
		      			var maxSize = {
					        width: 1200,
					        height: 1000,
					        level: 0.6
					    };
					    if(w > maxSize.width || h > maxSize.height){
					        var multiple = Math.max(w / maxSize.width, h / maxSize.height);
					        resizeW = w / multiple;
					        resizeH = h / multiple;
					        var canvas = document.createElement('canvas'),
						    ctx = canvas.getContext('2d');
					        canvas.width = resizeW;
					        canvas.height = resizeH;
					        ctx.drawImage(IMG, 0, 0, resizeW, resizeH);
						    var base64 = canvas.toDataURL('image/jpeg', maxSize.level);
						    $("#showImage")[0].src=base64;
						    var arr = base64.split(',');
				            base = arr[1];
				            console.log(base64)
					    } else {
					        // 如果图片尺寸小于最大限制，则不压缩直接上传
					        $("#showImage")[0].src=IMG.src;
				            var arr = IMG.src.split(',');
				            base = arr[1];
				            console.log(base);
					    }
					    
				    }
	        	
	            //console.log(this.result); //这个就是base64的数据了
		            // $("#showImage")[0].src=this.result;
		            // var arr = this.result.split(',');
		            // base = arr[1];
		            // console.log(base);
	            }
	        };
	    })(e.target.files[0]);
	    reader.readAsDataURL(e.target.files[0]);
	}

	$(".turn").on('tap',function(){
		var page = $(this).attr('data-turn');
		$('.release').hide();
		$(".release[data-rid='"+page+"']").fadeIn(200);
	});

	$('.push').on('tap',function(){
		layer.msg("发布成功！",{time:2000});
		setTimeout("window.location.href = '/manager/index'",2000);
	});

	// $("#addaddress").on('tap',function(){
	// 	indexAddress = layer.open({
	// 		type: 1,
	// 		title:false,
	// 		closeBtn:true,
	// 		content: $("#Address"),
	// 		area: ['90%', 'auto'],
	// 		shadeClose: false,
	// 		time:0
	// 	}); 
	// });

	function G(id) {
		return document.getElementById(id);
	}

	var map = new BMap.Map("allmap");            // 创建Map实例
	map.centerAndZoom("深圳",12);
	var ac = new BMap.Autocomplete(    //建立一个自动完成的对象
		{"input" : "inputAddress"
		,"location" : map
	});

	ac.addEventListener("onhighlight", function(e) {  //鼠标放在下拉列表上的事件
	var str = "";
		var _value = e.fromitem.value;
		var value = "";
		if (e.fromitem.index > -1) {
			value = _value.province +  _value.city +  _value.district +  _value.street +  _value.business;
		}    
		str = "FromItem<br />index = " + e.fromitem.index + "<br />value = " + value;
		
		value = "";
		if (e.toitem.index > -1) {
			_value = e.toitem.value;
			value = _value.province +  _value.city +  _value.district +  _value.street +  _value.business;
		}    
		str += "<br />ToItem<br />index = " + e.toitem.index + "<br />value = " + value;
		//G("searchResultPanel").innerHTML = str;
	});

	var myValue;
	ac.addEventListener("onconfirm", function(e) {    //鼠标点击下拉列表后的事件
	var _value = e.item.value;
		myValue = _value.province +  _value.city +  _value.district +  _value.street +  _value.business;
		//G("searchResultPanel").innerHTML ="onconfirm<br />index = " + e.item.index + "<br />myValue = " + myValue;
		
		setPlace();
	});

	function setPlace(){
		map.clearOverlays();    //清除地图上所有覆盖物
		function myFun(){
			var pp = local.getResults().getPoi(0).point;    //获取第一个智能搜索的结果
			map.centerAndZoom(pp, 18);
			map.addOverlay(new BMap.Marker(pp));    //添加标注
		}
		var local = new BMap.LocalSearch(map, { //智能搜索
		  onSearchComplete: myFun
		});
		local.search(myValue);
	}

	//map.setCurrentCity("深圳");
	// var local = new BMap.LocalSearch(map, {
	// 	renderOptions: {map: map, panel: "r-result"}
	// });
	//local.search("广东省深圳市南山区新能源");

	// $("#inputAddress").on('input propertychange',function(){
	// 	var val = $(this).val();
	// 	local.search(val);
	// })

	// var vm = new Vue({
 //        el: '#addaddress',
 //        data: {
 //           inputtext : 0
 //        },
 //        methods: {
 //        },
 //        computed :{
 //        },
 //        watch : {
 //           inputtext:function(val) {
 //              this.inputtext = val;
 //              local.search(val);
 //           }
 //        }
 //     });

</script>
{% endblock %}
{% block footer %}
       
{% endblock %}