{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 发布岗位{% endblock %}

{% block content %}
<style type="text/css">
	body,html {
		background: #fff;
	}
	.statbox img.auto-center {
		max-width: 90%;
	}
	.resu {
		padding:0;
	}
	
	.imgbox {
	    margin: 0 auto;
	    margin-top: 10px;
	}
	.col-xs-6 button {
		display: block;
		width: 100%;
	    height: 3rem;
	    line-height: 2rem;
	    background: #f07527;
	    color: #fff;
	    font-size: 1.8rem;
	    text-align: center;
	    border-radius: 3rem;
	    margin: 0 auto;
	    margin-top: 2rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">发布岗位</h1>
	<a class="mui-pull-right" href="/manager/admin"><span class="mui-icon mui-icon-contact"></span></a>
</header>

<div class="mui-content" id="{{ data['jobinfo']['id'] }}">
	<div class="release boxcontain container" id="RelA" data-rid="1">
		<h2>发布兼职 (1)</h2>
		<div class="statbox">
			<img src="/public/img/relA.png" class="auto-center">
		</div>
		<div class="boxcontain mar10 resu">
			<div class="mui-input-row">
				<label>岗位类别</label>
				<input type="text" placeholder="请选择岗位类别" id="userJobfield" value="{{ data['jobinfo']['type'] }}" readonly="readonly">
			</div>
			<div class="mui-input-row">
				<label>性别要求</label>
				<input type="text" placeholder="请选择性别" id="jobsex" value="{{ data['jobinfo']['sex'] }}" readonly="readonly">
			</div>
			<div class="mui-input-row">
				<label>招聘人数</label>
				<input type="text" placeholder="请输入招聘人数" id="jobpeople" value="{{ data['jobinfo']['num'] }}">
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6 right">
				<button class="turn" data-turn="2">下一步</button>
			</div>
		</div>
	</div>
	<div class="release boxcontain container none" id="RelB" data-rid="2">
		<h2>发布兼职 (2)</h2>
		<div class="statbox">
			<img src="/public/img/relB.png" class="auto-center">
		</div>
		<div class="boxcontain mar10">
			<input type="text" placeholder="请输入职位名称" id="jobname" value="{{ data['jobinfo']['title'] }}">
			<pre class="texts hidepre" id="pre" value="{{ data['jobinfo']['content'] }}"></pre>
			<textarea class="texts" id="textarea" placeholder="请输入职位描述" value="">{{ data['jobinfo']['content'] }}</textarea>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<button class="beforeturn" data-turn="1">上一步</button>
			</div>
			<div class="col-xs-6">
				<button class="turn" data-turn="3">下一步</button>
			</div>
		</div>
	</div>
	<div class="release boxcontain container none" id="RelC" data-rid="3">
		<h2>发布兼职 (3)</h2>
		<div class="statbox">
			<img src="/public/img/relC.png" class="auto-center">
		</div>
		<div class="boxcontain mar10 resu">
			<div class="mui-input-row">
				<label>计薪方式</label>
				<input type="text" placeholder="请选择计薪方式" id="paytype" value="{{ data['jobinfo']['salary_type'] }}" readonly="readonly">
			</div>
			<div class="mui-input-row">
				<label>薪资</label>
				<input type="text" placeholder="请输入金额(元)" id="paymoney" value="{{ data['jobinfo']['salary'] }}">
			</div>
			<div class="mui-input-row">
				<label>结算时间</label>
				<input type="text" placeholder="请选择结算时间" id="paytime" value="{{ data['jobinfo']['salary_time'] }}" readonly="readonly">
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<button class="beforeturn" data-turn="2">上一步</button>
			</div>
			<div class="col-xs-6">
				<button class="turn" data-turn="4">下一步</button>
			</div>
		</div>
	</div>
	<div class="release boxcontain container none" id="RelD" data-rid="4">
		<h2>发布兼职 (4)</h2>
		<div class="statbox">
			<img src="/public/img/relD.png" class="auto-center">
		</div>
		<div class="boxcontain mar10 resu">
			<div class="mui-input-row">
				<label>开始日期</label>
				<input type="text" placeholder="请选择开始日期" id="jobstarday" value="{{ data['jobinfo']['start_date'] }}" data-options='{"type":"date","beginYear":2018,"endYear":2022}' readonly="readonly">
			</div>
			<div class="mui-input-row">
				<label>结束日期</label>
				<input type="text" placeholder="请选择结束日期" id="jobendday" value="{{ data['jobinfo']['end_date'] }}" data-options='{"type":"date","beginYear":2018,"endYear":2022}' readonly="readonly">
			</div>
			<div class="mui-input-row">
				<label>开始时间</label>
				<input type="text" placeholder="请选择开始时间" id="jobstartime" value="{{ data['jobinfo']['start_time'] }}" data-options='{"type":"time"}' readonly="readonly">
			</div>
			<div class="mui-input-row">
				<label>结束时间</label>
				<input type="text" placeholder="请选择结束时间" id="jobendtime" value="{{ data['jobinfo']['end_time'] }}" data-options='{"type":"time"}' readonly="readonly">
			</div>
			<div class="mui-input-row">
				<label>工作区域</label>
				<input type="text" placeholder="请选择工作区域" id="jobarea" value="{{ data['jobinfo']['province'] }}{{ data['jobinfo']['city'] }}{{ data['jobinfo']['district'] }}">
				<input type="hidden" id="jobprovince">
				<input type="hidden" id="jobcity">
				<input type="hidden" id="jobdistrict">
			</div>
			<div class="mui-input-row">
				<label>定位地址</label>
				<!-- <span class="btn btn-default fileinput-button">
		            <span>上传图片...</span>
		            <input type="button" id="addaddress">
		        </span> -->
				<input type="text" placeholder="添加工作地点" id="inputAddress" v-model="inputtext" value="{{ data['jobinfo']['address'] }}">
				<input type="hidden" id="lng">
				<input type="hidden" id="lat">
			</div>
			<div class="mui-input-row">
				<label>门牌号</label>
				<input type="text" placeholder="请输入门牌号（选填）" id="jobroom" value="{{ data['jobinfo']['roomno'] }}">
			</div>
			<!-- <div id="r-result"></div> -->
		</div>
		<div class="row">
			<div class="col-xs-6">
				<button class="beforeturn" data-turn="3">上一步</button>
			</div>
			<div class="col-xs-6">
				<button class="turn" data-turn="5">下一步</button>
			</div>
		</div>
	</div>
	<div class="release boxcontain container none" id="RelE" data-rid="5">
		<h2>发布兼职 (5)</h2>
		<div class="statbox">
			<img src="/public/img/relE.png" class="auto-center">
		</div>
		<div class="boxcontain mar10 resu">
			<div class="mui-input-row">
				<label>企业全称</label>
				{%if data['jobinfo']['id'] %}
				<input type="text" placeholder="请输入企业全称" id="companyname" value="{{ data['jobinfo']['company_name'] }}">
				{% else %}
				<input type="text" placeholder="请输入企业全称" id="companyname" value="{{ data['userinfo']['company_name'] }}">
				{% endif %}
			</div>
			<div class="mui-input-row">
				<label>联系人</label>
				{%if data['jobinfo']['id'] %}
				<input type="text" placeholder="请输入联系人姓名" id="companyman" value="{{ data['jobinfo']['real_name'] }}">
				{% else %}
				<input type="text" placeholder="请输入联系人姓名" id="companyman" value="{{ data['userinfo']['real_name'] }}">
				{% endif %}
			</div>
			<div class="mui-input-row">
				<label>联系电话</label>
				{%if data['jobinfo']['id'] %}
				<input type="text" placeholder="请输入联系电话" id="companytel" value="{{ data['jobinfo']['phone'] }}">
				{% else %}
				<input type="text" placeholder="请输入联系电话" id="companytel" value="{{ data['userinfo']['phone'] }}">
				{% endif %}
			</div>
			<div class="mar10">
				<label>微信二维码</label>
				<span class="btn btn-default fileinput-button">
		            <span>上传图片...</span>
		            <input type="file" accept="image/*" onchange="imgChange(event)" id="file">
		        </span>
		        <div class="imgbox rel">
		        	{%if data['jobinfo']['id'] %}
					<img src="{{ data['jobinfo']['wxcode_img'] }}" class="auto-center" id="showImage">
					{% else %}
					<img src="{{ data['userinfo']['wxcode_img'] }}" class="auto-center" id="showImage">
					{% endif %}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-6">
				<button class="beforeturn" data-turn="4">上一步</button>
			</div>
			<div class="col-xs-6">
				<button class="push">发布</button>
			</div>
		</div>
	</div>
</div>

<!-- <div id="Address" class="boxcontain container">
	<input type="text" placeholder="请输入地址" id="addressText" value="">
	
</div> -->

<div id="allmap"></div>
<script type="text/javascript">

	//index 1
	var jobtype;
	var jobsex;
	var jobpeople;

	//index 2
	var jobname;
	var content;

	//index 3
	var paytype;
	var paymoney;
	var paytime;

	//index 4
	var jobstarday;
	var jobendday;
	var jobstartime;
	var jobendtime;

	var lng = "{{ data['jobinfo']['lng'] }}";	//经度
	var lat = "{{ data['jobinfo']['lat'] }}";	//纬度
	var province = "{{ data['jobinfo']['province'] }}";
	var city = "{{ data['jobinfo']['city'] }}";
	var district = "{{ data['jobinfo']['district'] }}";
	var address = "{{ data['jobinfo']['address'] }}";
	var jobroom;

	//index 5
	var companyname;
	var companyman;
	var companytel;

	var textarea = document.getElementById('textarea');
	var pre = document.getElementById('pre');

	textarea.oninput = function() {
	    pre.textContent = textarea.value;
	    textarea.style.height = pre.offsetHeight + 'px';
	}

	var base;

	$(function(){
		var src = $("#showImage").attr('src');
		if(src != ''){
			$('.imgbox').css({"width":"8rem","height":"8rem"});
			main(src);
		}
	});

	function getBase64Image(img) {
        var canvas = document.createElement("canvas");
        canvas.width = img.width;
        canvas.height = img.height;
        var ctx = canvas.getContext("2d");
        ctx.drawImage(img, 0, 0, img.width, img.height);
        var dataURL = canvas.toDataURL("image/png");
        base = dataURL;
        console.log(base);
        //return dataURL; // return dataURL.replace("data:image/png;base64,", ""); 
    }
    function main(srcA) { 
        var img = document.createElement('img'); 
        img.src = srcA; 
        img.onload =function() { 
            var data = getBase64Image(img); 
        } 
    }

	function imgChange(e) {
	    var reader = new FileReader();
	    reader.onload = (function (file) {
	        return function (e) {
	        	if(e.total>10*1024*1024){
			        //alert('上传的图片的大于4M,请重新选择');
			        layer.msg('上传的图片的大于10M,请重新选择。',{icon: 5});
			        return false;
		        } else {
		        	$('.imgbox').css({"width":"8rem","height":"8rem"});
		        	var IMG = new Image();
		        	IMG.src = this.result;
		        	var arA = this.result.split(';');
		        	var arB = arA[0].split('/');
		        	var arC = arB[1];
		            IMG.onload = function(){
	      				var w = this.naturalWidth, h = this.naturalHeight , resizeW = 0, resizeH = 0;
	      				console.log(w,h)
	      			
		      			var maxSize = {
					        width: 1200,
					        height: 1000,
					        level: 0.6
					    };
					    if(w > maxSize.width || h > maxSize.height){
					        var multiple = Math.max(w / maxSize.width, h / maxSize.height);
					        resizeW = w / multiple;
					        resizeH = h / multiple;
					        var canvas = document.createElement('canvas'),
						    ctx = canvas.getContext('2d');
					        canvas.width = resizeW;
					        canvas.height = resizeH;
					        ctx.drawImage(IMG, 0, 0, resizeW, resizeH);
						    var base64 = canvas.toDataURL("image/"+arC, maxSize.level);
						    $("#showImage")[0].src=base64;
				            base = base64
				            console.log(base)
					    } else {
					        // 如果图片尺寸小于最大限制，则不压缩直接上传
					        $("#showImage")[0].src=IMG.src;
				            //var arr = IMG.src.split(',');
				            base = IMG.src;
				            console.log(base);
					    }   
				    }
	            }
	        };
	    })(e.target.files[0]);
	    reader.readAsDataURL(e.target.files[0]);
	}

	function checkTime(checkStartDate, checkEndDate){
		var arys1 = new Array();      
		var arys2 = new Array();      
		if(checkStartDate != null && checkEndDate != null) {      
			arys1 = checkStartDate.split('-');      
			var sdate=new Date(arys1[0],parseInt(arys1[1]-1),arys1[2]);      
			arys2 = checkEndDate.split('-');      
			var edate=new Date(arys2[0],parseInt(arys2[1]-1),arys2[2]);      
			if(sdate > edate) {            
				return false;         
			} else {     
				return true;      
			}   
		}      
	}

	function showNextPage(page){
		$('.release').hide();
		$(".release[data-rid='"+page+"']").fadeIn(200);
	}

	$(".beforeturn").on('tap',function(){
		var page = $(this).attr('data-turn');
		showNextPage(page);
	});

	$("#RelA .turn").on('tap',function(){
		var page = $(this).attr('data-turn');

		jobtype = $("#userJobfield").val();
		if(jobtype.length == ''){
	        layer.msg('请选择岗位类别。');
	        return false;
	    }

	    jobsex = $("#jobsex").val();
	    if(jobsex.length == ''){
	        layer.msg('请选择性别。');
	        return false;
	    }

	    jobpeople = $("#jobpeople").val();
	    if($.trim(jobpeople).length == '' || jobpeople == '0'){
	        layer.msg('请填写招聘人数。');
	        return false;
	    }

		showNextPage(page);
	});

	$("#RelB .turn").on('tap',function(){
		var page = $(this).attr('data-turn');

		jobname = $("#jobname").val();
		if(jobname.length == ''){
	        layer.msg('请填写职位名称。');
	        return false;
	    }

	    content = $("#textarea").val();
	    if(content.length == ''){
	        layer.msg('请填写职位描述。');
	        return false;
	    }

		showNextPage(page);
	});

	$("#RelC .turn").on('tap',function(){
		var page = $(this).attr('data-turn');

		paytype = $("#paytype").val();
		if(paytype.length == ''){
	        layer.msg('请选择计薪方式。');
	        return false;
	    }

	    paymoney = $("#paymoney").val();
	    if(paymoney.length == '' || paymoney < 0){
	        layer.msg('请填写薪资。');
	        return false;
	    }

	    paytime = $("#paytime").val();
	    if(paytime.length == ''){
	        layer.msg('请选择结算时间。');
	        return false;
	    }

		showNextPage(page);
	});

	$("#RelD .turn").on('tap',function(){
		var page = $(this).attr('data-turn');

		jobstarday = $("#jobstarday").val();
		if(jobstarday.length == ''){
	        layer.msg('请选择开始日期。');
	        return false;
	    }

	    jobendday = $("#jobendday").val();
	    if(jobendday.length == ''){
	        layer.msg('请选择结束日期。');
	        return false;
	    }

	    if(!checkTime(jobstarday,jobendday)){
	    	layer.msg('开始日期不能大于结束日期。');
	        return false;
	    }

	    jobstartime = $("#jobstartime").val();
	    if(jobstartime.length == ''){
	        layer.msg('请选择开始时间。');
	        return false;
	    }

	    jobendtime = $("#jobendtime").val();
	    if(jobendtime.length == ''){
	        layer.msg('请选择结束时间。');
	        return false;
	    }

	    var jobarea = $("#jobarea").val();
	    if(jobarea.length == ''){
	        layer.msg('请选择工作区域。');
	        return false;
	    }

	    jobroom = $("#jobroom").val();

	    if(!lng || lng == ''){
	    	layer.msg('请选择定位地址。');
	        return false;
	    }

		showNextPage(page);
	});

	$('.push').on('tap',function(){

		companyname = $("#companyname").val();
		if(companyname.length == ''){
	        layer.msg('请填写企业名称。');
	        return false;
	    }

	    companyman = $("#companyman").val();
	    if(companyman.length == ''){
	        layer.msg('请填写联系人。');
	        return false;
	    }

	    companytel = $("#companytel").val();
	    if(companytel.length == ''){
	        layer.msg('请填写联系人电话。');
	        return false;
	    }

	    if(!base || base == ''){
	    	layer.msg('请上传微信二维码。');
	        return false;
	    }

		indexload = layer.load(2, {
		  shade: [0.4,'#000'] //0.1透明度的白色背景
		});

		if($('.mui-content').attr('id') == ''){
		
			$.post('/manager/addjob',{
				'title':jobname,
				'province':province,
				'city':city,
				'district':district,
				'address':address,
				'roomno':jobroom,
				'lng':lng,
				'lat':lat,
				'content':content,
				'type':jobtype,
				'sex':jobsex,
				'num':jobpeople,
				'salary_type':paytype,
				'salary':paymoney,
				'salary_time':paytime,
				'start_date':jobstarday,
				'end_date':jobendday,
				'start_time':jobstartime,
				'end_time':jobendtime,
				'real_name':companyman,
				'company_name':companyname,
				'phone':companytel,
				'wxcode_img':base
			},function(data){
				if(data.error_code == '0'){
					layer.close(indexload);
					mui.alert('您已成功发布一个新岗位。', '发布成功！',function(){
						window.location.href = "/manager/admin";
					});
				} else {
					layer.close(indexload);
					layer.msg(data.reason);
				}
			},'json');

		} else {
			var jobid = $('.mui-content').attr('id');

			$.post('/manager/addjob',{
				'jobid':jobid,
				'title':jobname,
				'province':province,
				'city':city,
				'district':district,
				'address':address,
				'roomno':jobroom,
				'lng':lng,
				'lat':lat,
				'content':content,
				'type':jobtype,
				'sex':jobsex,
				'num':jobpeople,
				'salary_type':paytype,
				'salary':paymoney,
				'salary_time':paytime,
				'start_date':jobstarday,
				'end_date':jobendday,
				'start_time':jobstartime,
				'end_time':jobendtime,
				'real_name':companyman,
				'company_name':companyname,
				'phone':companytel,
				'wxcode_img':base
			},function(data){
				if(data.error_code == '0'){
					layer.close(indexload);
					mui.alert('您已成功修改该岗位。', '修改成功！',function(){
						window.location.href = "/manager/admin";
					});
				} else {
					layer.close(indexload);
					layer.msg(data.reason);
				}
			},'json');

		}
	});

	$("#inputAddress").on('tap',function(){
		var cityA = $("#jobcity").val();
		AMap.plugin('AMap.Autocomplete',function(){//回调函数
		    var autoOptions = {
		        city: cityA, //城市，默认全国
		        citylimit: true,
		        input:"inputAddress"//使用联想输入的input的id
		    };
		    var autocomplete= new AMap.Autocomplete(autoOptions);

		    AMap.event.addListener(autocomplete, "select", function(data){
		        console.log(data)
		        var area = data.poi.district;
		        var arrC = data.poi.district.split('市');
		        if(!arrC[1]){
		        	area = area+$("#jobdistrict").val();
		        }
		        address = data.poi.name;
		        console.log(address)
		        lng = data.poi.location.lng;
		        lat = data.poi.location.lat;
		        console.log(area,address,lng,lat)
		        $("#jobarea").val(area);

		        var arr = area.split('省');
		        province = arr[0]+"省";
		        //console.log(province);
		        var arrB = arr[1].split('市');
		        city = arrB[0]+"市";
		        district = arrB[1];
		        //$("#jobdistrict").val('南山区');
		    }); 
		});
	})
	

</script>
{% endblock %}
{% block footer %}
       
{% endblock %}