{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 报名管理{% endblock %}

{% block content %}
<style type="text/css">
	.signselect {
		background: #fff;
		border-bottom: 1px solid #cbcbcb !important;
	}
	.signselect .mui-control-item.mui-active {
		color: #f07527 !important;
    	border-bottom: 2px solid #f07527 !important;
	}
	.joblist .signs {
		border-bottom: 1px solid #ececec;
    	background: #fff;
    	margin-bottom: 10px;
	}
	.joblist .signs > a {
	    white-space: inherit;
	}
	.joblist .signs .userinfo {
		padding: 1rem 0 0 0;
	    position: relative;
	    color: #3b3b3b;
	    height: auto;
	}
	.joblist .signs .userinfo .userimg {
	    width: 20%;
   		padding: 9.5%;
	    position: relative;
	    overflow: hidden;
	    border-radius: 50%;
	    border: 2px solid #fff;
	    margin-right: 1rem;
	}
	.joblist .signs .userinfo .info .name {
		font-weight: 300;
		margin-bottom: 5px;
		font-size:1.6rem;
	}
	.joblist .signs .userinfo .else {
		margin-left: 10px;
    	line-height: 1.8rem;
	}
	.joblist .signs .userinfo .tips span {
		display: inline-block;
		color:#fff;
		background: #f07527;
		padding:2px 5px;
		margin-right: 5px;
		margin-bottom: 5px;
		float:left;
		font-size:1rem;
		height:auto;
		border-radius: 5px;
	}
	.joblist .signs .rows {
		border-top:1px solid #eee;
		padding-top:5px;
	}
	.joblist .signs .rows button {
		float:right;
		width: 25%;
		padding:5px;
		border-radius: 5px;
		margin-left:5px;
		font-size:1rem;
	}
	.joblist .signs .rows button.agree,
	.joblist .signs .rows button.assess,
	.joblist .signs .rows button.complain {
		background: #f07527;
		border:1px solid #f07527;
		color:#fff;
	}
	.joblist .signs .rows a {
		border:1px solid #ccc;
		float:right;
		width: 25%;
		padding:5px;
		border-radius: 5px;
		margin-left:5px;
		font-size:1rem;
		color: #000;
    	text-align: center;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">报名管理</h1>
</header>

<div class="mui-content">
	<div id="segmentedControl" class="mui-segmented-control mui-segmented-control-inverted mui-segmented-control-primary signselect">
		<a href="#item1" class="mui-control-item mui-active">已报名</a>
		<a href="#item2" class="mui-control-item">已录用</a>
		<a href="#item3" class="mui-control-item">已拒绝</a>
	</div>
	<div id="Signlist">
		<div id="item1" class="mui-control-content mui-active">
			<ul class="mui-table-view joblist">
				{% for key, item in data['apply'] %}
					<li class="mui-table-view-cell signs" idvalue="{{ item['id'] }}">
						<a href="userresume?applyid={{ item['id'] }}">
							<h4>{{ item['title'] }}</h4>
							<div class="userinfo clearfix">
								<div class="userimg left">
									<img src="{{ item['headimgurl'] }}" class="auto-center">
								</div>
								<div class="info left">
									<div class="name left">{{ item['real_name'] }}</div>
									<!--<div class="else left">
										<span class="score">4.9</span>52单
									</div>
									<div class="cls"></div>
									<div class="tips clearfix">
										<span>效率高</span>
										<span>准时</span>
										<span>负责任</span>
										<span>效率高</span>
										<span>准时</span>
										<span>负责任</span>
									</div>-->
								</div>
							</div>
						</a>
						{% if item['type'] == 'Wait' %}
							<div class="rows clearfix">
								<button class="agree apply" data-type="Y" data-id="{{ item['id'] }}">录用</button>
								<button class="reject apply" data-type="N" data-id="{{ item['id'] }}">拒绝</button>
								<a class="none telephone" href="tel:{{ item['phone'] }}">联系他/她</a>
							</div>
						{% elseif item['type'] == 'N' %}
							<div class="rows clearfix">
								<a class="telephone" href="tel:{{ item['phone'] }}">联系他/她</a>
							</div>
						{% elseif item['type'] == 'Y' %}
							<div class="rows clearfix">
								<a class="telephone" href="tel:{{ item['phone'] }}">联系他/她</a>
							</div>
						{% endif %}
					</li>
				{% endfor %}
			</ul>
		</div>
		<div id="item2" class="mui-control-content">
			<ul class="mui-table-view joblist">
				{% for key, item in data['apply'] %}
				{% if item['type'] == 'Y' %}
					<li class="mui-table-view-cell signs" idvalue="{{ item['id'] }}">
						<a href="userresume?applyid={{ item['id'] }}">
							<h4>{{ item['title'] }}</h4>
							<div class="userinfo clearfix">
								<div class="userimg left">
									<img src="{{ item['headimgurl'] }}" class="auto-center">
								</div>
								<div class="info left">
									<div class="name left">{{ item['real_name'] }}</div>
									<!--<div class="else left">
										<span class="score">4.9</span>52单
									</div>
									<div class="cls"></div>
									<div class="tips clearfix">
										<span>效率高</span>
										<span>准时</span>
										<span>负责任</span>
										<span>效率高</span>
										<span>准时</span>
										<span>负责任</span>
									</div>-->
								</div>
							</div>
						</a>
						<div class="rows clearfix">
							<a class="telephone" href="tel:{{ item['phone'] }}">联系他/她</a>
						</div>
					</li>
				{% endif %}
				{% endfor %}
			</ul>
		</div>
		<div id="item3" class="mui-control-content">
			<ul class="mui-table-view joblist">
				{% for key, item in data['apply'] %}
				{% if item['type'] == 'N' %}
				<li class="mui-table-view-cell signs" idvalue="{{ item['id'] }}">
					<a href="userresume?applyid={{ item['id'] }}">
						<h4>{{ item['title'] }}</h4>
						<div class="userinfo clearfix">
							<div class="userimg left">
								<img src="{{ item['headimgurl'] }}" class="auto-center">
							</div>
							<div class="info left">
								<div class="name left">{{ item['real_name'] }}</div>
								<!--<div class="else left">
                                    <span class="score">4.9</span>52单
                                </div>
                                <div class="cls"></div>
                                <div class="tips clearfix">
                                    <span>效率高</span>
                                    <span>准时</span>
                                    <span>负责任</span>
                                    <span>效率高</span>
                                    <span>准时</span>
                                    <span>负责任</span>
                                </div>-->
							</div>
						</div>
					</a>
					<div class="rows clearfix">
						<a class="telephone" href="tel:{{ item['phone'] }}">联系他/她</a>
					</div>
				</li>
				{% endif %}
				{% endfor %}
			</ul>
		</div>
	</div>
</div>

<script type="text/javascript">

	$(".apply").on('tap',function(){
		var _this = $(this);
		var id = _this.attr('data-id');
		var type = _this.attr('data-type');
		var con = _this.parent().find('button');
		var tel = _this.parent().find('a.none');
		if(type == "Y"){
			var btnArray = ['取消', '确认'];
			mui.confirm("您是否要录用该报名者？", '确认录用', btnArray, function(e) {
				if (e.index == 1) {
					$.get('/manager/changeapply',{'applyid':id , 'type':type},function(data){
						if(data.error_code == '0'){
							layer.msg('录用成功。');
							con.hide();
							tel.show();
							var par = _this.parents('.signs');
							$("#item2 .joblist").append(par).clone();
						} else {
							layer.msg(data.reason);
						}
					},'json');
				} else {

				}
			})
		}

		if(type == "N"){
			var btnArray = ['取消', '确认'];
			mui.confirm("您是否要拒绝该报名者？", '是否拒绝', btnArray, function(e) {
				if (e.index == 1) {
					$.get('/manager/changeapply',{'applyid':id , 'type':type},function(data){
						if(data.error_code == '0'){
							layer.msg('已拒绝该报名者。');
							con.hide();
							tel.show();
							var par = _this.parents('.signs');
							$("#item3 .joblist").append(par).clone();
						} else {
							layer.msg(data.reason);
						}
					},'json');
				} else {

				}
			})
		}
	});


</script>

{% endblock %}
{% block footer %}
       
{% endblock %}