{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 查看简历{% endblock %}

{% block content %}
<style type="text/css">
	#usertop {
		background: -webkit-linear-gradient(to bottom right , #ff2020, #f07527, #fedc2b);
	    background: -o-linear-gradient(to bottom right , #ff2020, #f07527, #fedc2b);
	    background: -moz-linear-gradient(to bottom right , #ff2020, #f07527, #fedc2b);
	    background: linear-gradient(to bottom right , #ff2020, #f07527, #fedc2b);
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">查看简历</h1>
	<a class="mui-pull-right" href="/manager/admin"><span class="mui-icon mui-icon-contact"></span></a>
</header>

<div class="mui-content">
	<div id="usertop">
		<div class="userinfo clearfix">
			<div class="userimg left">
				<img src="{{ data['userinfo']['headimgurl'] }}" class="auto-center">
			</div>
			<div class="info">
				<div class="name">{{ data['userinfo']['real_name'] }}</div>
				<!--<div class="else"><span class="score">4.9</span>52单</div>
				<div class="tips clearfix">
					<span>效率高</span>
					<span>准时</span>
					<span>负责任</span>
					<span>效率高</span>
					<span>准时</span>
					<span>负责任</span>
				</div>-->
			</div>
		</div>
	</div>
	<div id="userresume">
		<div class="resu">
			<div class="mui-input-row">
				<label>性别</label>
				<p>{{ data['userinfo']['sex'] }}</p>
			</div>
			<div class="mui-input-row">
				<label>生日</label>
				<p>{{ data['userinfo']['birth'] }}</p>
			</div>
			<div class="mui-input-row">
				<label>身份</label>
				<p>{{ data['userinfo']['identity'] }}</p>
			</div>
			<div class="mui-input-row">
				<label>学历</label>
				<p>{{ data['userinfo']['education'] }}</p>
			</div>
			<div class="mui-input-row">
				<label>手机号码</label>
				<p>{{ data['userinfo']['phone'] }}</p>
			</div>
			<div class="mui-input-row">
				<label>工作经验</label>
				<p>{{ data['userinfo']['experience'] }}</p>
			</div>
			<div class="mui-input-row">
				<label>工作领域</label>
				<p>{{ data['userinfo']['workarea'] }}</p>
			</div>
		</div>
	</div>
</div>

{% endblock %}
{% block footer %}
       
{% endblock %}