{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职之家 - 关于我们{% endblock %}

{% block content %}
<style type="text/css">
	
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">关于我们</h1>
</header>

<div class="mui-content">
	<div id="aboutus">
		<img src="/public/img/aboutus.png">
		<p>兼职之家是国内第一个基于区块链信用记录的兼职平台。我们为每一位雇主/督导及报名兼职的雇员建立基于区块链技术的双向智能合约,真实且不可篡改地将雇主/督导及雇员的评价与信用记录在区块链上，基于雇主和雇员公开透明的信用记录，帮助雇员选到信用更好的雇主（督导）。也帮助雇主找到信用更好雇员。</p>
		<p>同时，我们会将积分以多种方式奖励给信用更好的雇主与雇员，收获的积分可用于兑换话费及流量等丰富商品，我们持续为高信用的雇主和雇员送出更多的福利！</p>
		<p>我们希望最终在兼职之家平台上留存下来的雇主和雇员都是高信用、值得信赖的。</p>
	</div>
</div>

{% endblock %}
{% block footer %}
       
{% endblock %}