{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职之家 - 关于我们{% endblock %}

{% block content %}
<style type="text/css">
	#aboutus {
		padding:100px 15px;
		height:100%;
		background: #fff;
	}
	#aboutus img {
		width: 8.5rem;
		height:8.5rem;
		margin:0 auto;
		margin-bottom: 2rem;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">关于我们</h1>
</header>

<div class="mui-content">
	<div id="aboutus">
		<img src="/public/img/aboutus.png">
	</div>
</div>

{% endblock %}
{% block footer %}
       
{% endblock %}