{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 绑定手机{% endblock %}

{% block content %}
<style type="text/css">
	
	
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">绑定手机</h1>
</header>

<div class="mui-content">
	<!--未绑定-->
	<div id="nobind" class="resu" style="margin-top:1rem;">
		<div class="mui-input-row">
			<label>手机号</label>
			<input type="text" placeholder="请输入您的手机号" value="{{ data['userinfo']['phone'] }}" id="telphone">
		</div>
		<div class="mui-input-row">
			<input type="number" name="captcha" placeholder="请输入短信验证码" id="captcha">
			<button class="getcaptcha">获取验证码</button>
			<button class="waiting none"></button>
		</div>
	</div>
	<button class="footbtn" id="TelBind">绑定</button>
</div>

<script type="text/javascript">

	$('.getcaptcha').on('tap',function(){
		var mobile = $("#telphone").val();
		if(mobile.length == ''){
	        layer.msg('请填写手机号。');
	        return false;
	    }
		if(mobile.length != 11){
	        layer.msg('手机号长度不正确。');
	        return false;
	    }
	    if(!checkMobile(mobile)){
	    	layer.msg('请输入正确的手机号。');
        	return false;
        }

        $(this).attr('disabled','disabled');
        $.get('/job/getphonecode',{'mobile':mobile},function(data){
			if(data.error_code == '0'){
				mobileMsg();
			} else {
				layer.msg(data.reason);
			}
		},'json');
	});

	$("#TelBind").on('tap',function(){
		var mobile = $("#telphone").val();
		if(mobile.length == ''){
	        layer.msg('请填写手机号。');
	        return false;
	    }
		if(mobile.length != 11){
	        layer.msg('手机号长度不正确。');
	        return false;
	    }
	    if(!checkMobile(mobile)){
	    	layer.msg('请输入正确的手机号。');
        	return false;
        }

		var captcha = $("#captcha").val();
		if(captcha.length == ''){
	        layer.msg('请填写验证码。');
	        return false;
	    }

	    $(this).attr('disabled','disabled');
	    $.get('/job/edituserinfo',{'mobile':mobile,'vcode':captcha},function(data){
			if(data.error_code == '0'){
				layer.msg('绑定成功！');
				setTimeout("window.location.href = '/job/user'",2000);
			} else {
				layer.msg(data.reason);
			}
		},'json');
	});

</script>

{% endblock %}
{% block footer %}
       
{% endblock %}