{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职之家 - 绑定手机{% endblock %}

{% block content %}
<style type="text/css">
	
	
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">绑定手机</h1>
</header>

<div class="mui-content">
	<!--未绑定-->
	<div id="nobind" class="resu">
		<div class="mui-input-row">
			<label>手机号</label>
			<input type="text" placeholder="请输入您的手机号">
		</div>
		<div class="mui-input-row">
			<input type="text" placeholder="请输入短信验证码">
			<button>获取验证码</button>
		</div>
	</div>
	<button class="footbtn" id="TelBind">绑定</button>
</div>

{% endblock %}
{% block footer %}
       
{% endblock %}