{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职之家 - 职位详情{% endblock %}

{% block content %}
<style type="text/css">
	.contain > div {
		margin-bottom: 1rem;
		background: #fff;
		padding:15px;
	}
	footer {
		position: fixed;
		left:0;
		bottom:0;
		height:3rem;
		width: 100%;
	}
	footer a {
		display: block;
		height:3rem;
		line-height: 1.6rem;
		font-size:1.6rem;
		float:left;
		padding:10px;
		text-align: center;
	}
	footer a.collect {
		width: 40%;
		background: #fff1dc;
		color:#353638;
	}
	footer a.sign {
		width: 60%;
		background: #f07527;
		color:#fff;
		float: none;
	    margin: 0 auto;
	    position: relative;
	    bottom: 20px;
	}
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">职位详情</h1>
</header>

<div class="mui-content">
	<div class="contain">
		<div id="detail">
			<h1><strong>{{ data['jobinfo']['title'] }}</strong></h1>
			<h3>{{ data['jobinfo']['salary'] }}元/{{ data['jobinfo']['salary_type'] }}</h3>
			<div class="info"><span class="spen">{{ data['jobinfo']['salary_time'] }}</span><span class="spen">{{ data['jobinfo']['type'] }}</span>{{ data['jobinfo']['num'] }}人</div>
			<hr>
			<h2>职位详情</h2>
			<h4>职位描述</h4>
			<p>{{ data['jobinfo']['content'] }}</h4>
			<p><span class="spen">{{ data['jobinfo']['salary_time'] }}</span>{{ data['jobinfo']['salary'] }}元/{{ data['jobinfo']['salary_type'] }}</p>
			<h4>工作时间</h4>
			<p>开始日期：<span>{{ data['jobinfo']['start_date'] }}</span></p>
			<p>结束日期：<span>{{ data['jobinfo']['end_date'] }}</span></p>
			<div class="time">{{ data['jobinfo']['start_time'] }} ~ {{ data['jobinfo']['end_time'] }}</div>
			<div class="cls"></div>
			<hr>
			<ul class="mui-table-view">
				<li class="mui-table-view-cell">
					<a class="mui-navigate-right">
						<div>工作地点</div>
						<div>{{ data['jobinfo']['province'] }}{{ data['jobinfo']['city'] }}{{ data['jobinfo']['district'] }}{{ data['jobinfo']['address'] }}{{ data['jobinfo']['roomno'] }}</div>
					</a>
				</li>
			</ul>
		</div>
		<div id="leader">
			<ul class="mui-table-view">
				<li class="mui-table-view-cell">
					<a class="mui-navigate-right">
						<div class="imgbox left">
							<img src="{{ data['jobinfo']['wxcode_img'] }}" class="auto-center">
						</div>
						<div class="infos left">
							<div class="ltc"><span>{{ data['jobinfo']['real_name'] }}</span>{{ data['jobinfo']['company_name'] }}</div>
							<!-- <div><span class="score">4.8</span>50人评价</div> -->
						</div>
					</a>
				</li>
			</ul>
		</div>
		<div id="tips">
			<p>防骗提示：未标明收费的职位不会收取任何费用，若商家要求费用或押金，请提高警惕并第一时间向我们举报。<a href="">去投诉</a></p>
		</div>
		<br>
		<br>
		<br>
		<br>
		<footer>
			<a href="#" class="collect none">收藏</a>
			<a href="/job/signdone" class="sign">立即报名</a>
		</footer>
	</div>
</div>

{% endblock %}
{% block footer %}
       
{% endblock %}