{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 职位详情{% endblock %}

{% block content %}
<style type="text/css">
	body,html {
		position: relative;
	}
	.contain > div {
		margin-bottom: 1rem;
		background: #fff;
		padding:15px;
	}
	footer {
		position: fixed;
		left:0;
		bottom:0;
		height:7rem;
		width: 100%;
	}
	footer a {
		display: block;
		height:3rem;
		line-height: 1.6rem;
		font-size:1.6rem;
		float:left;
		padding:10px;
		text-align: center;
	}
	footer a.collect,
	footer a.share {
		width: 40%;
		background: #fff1dc;
		color:#353638;
	}
	/*footer a.collect,
	footer a.share {
		width: 20%;
		background: #fff1dc;
		color:#353638;
	}*/
	footer a.sign {
		width: 60%;
		background: #f07527;
		color:#fff;
		float: none;
	    margin: 0 auto;
	    position: relative;
	    bottom: 20px;
	    border-radius: 3rem;
	}
	#Btn {
		position: absolute;
		top:60px;
		right: 13px;
		z-index:8;
		width: 48%;
	}
	#Btn button,
	#Btn a {
		display: block;
		float:right;
		border:1px solid #f07527;
		padding:3px 5px;
		color:#f07527;
		font-size:1rem;
		line-height: 1rem;
		text-align: center;
	    margin-left: 5px;
	    border-radius: 3px;
	}
	#mask {
		position: absolute;
		top:0;
		right:0;
		width: 100%;
		height: 100%;
		background: rgba(0,0,0,.8);
		z-index:12;
		display: none;
	}
	#mask img {
		width: 100%;
		display: block;
	}
	#detailAD {
		position: fixed;
		left:0;
		bottom:0;
		width: 100%;
		/*height:5rem;*/
		background: #e70101;
	}
	#detailAD img {
		display: block;
		max-width: 100%;
		/*height:100%;*/
		margin:0 auto;
	}
	#detailAD .closead {
		position: absolute;
		top:0;
		right:0px;
		width: 2rem;
		height:100%;
		color:#fff;
	}
	#detailAD .closead span {
		height:2rem;
	}
</style>

<div id="Btn">
	<a href="/job/index">更多兼职</a>
	<button class="share">分享</button>
</div>

<div id="mask">
	<img src="/public/img/share.png">
</div>

<header class="mui-bar mui-bar-nav">
	<a class="backtoindex mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">职位详情</h1>
	<a href="/job/user" class="mui-pull-right"><span class="mui-icon mui-icon-contact"></span></a>
</header>

<div class="mui-content">
	<div class="contain">
		<div id="detail" class="rel">
			<h1>{{ data['jobinfo']['title'] }}</h1>
			<h3>{{ data['jobinfo']['salary'] }}元/{{ data['jobinfo']['salary_type'] }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;浏览人数：{{ data['jobinfo']['view_num'] }}人</h3>
			<p><span class="title">兼职类型：</span>{{ data['jobinfo']['type'] }}</p>
			<p><span class="title">招聘人数：</span>{{ data['jobinfo']['num'] }}人</p>
			<p><span class="title">结算方式：</span>{{ data['jobinfo']['salary_time'] }}</p>
			<p><span class="title">基本工资：</span>{{ data['jobinfo']['salary'] }}元/{{ data['jobinfo']['salary_type'] }}</p>
			<hr>
			<h2>工作内容</h2>
			<p class="content">{{ data['jobinfo']['content2'] }}</h4>
			<hr>
			<h2>工作时间</h4>
			<p><span class="title">开始日期：</span><span>{{ data['jobinfo']['start_date'] }}</span></p>
			<p><span class="title">结束日期：</span><span>{{ data['jobinfo']['end_date'] }}</span></p>
			{%if data['jobinfo']['start_time'] == '无'%}
			{% else %}
			<p><span class="title">上班时段：</span><span class="time">{{ data['jobinfo']['start_time'] }} ~ {{ data['jobinfo']['end_time'] }}</span></p>
			{% endif %}
			<div class="cls"></div>
			<hr>
			<h2>工作地点</h2>
			<br>
			<ul class="mui-table-view">
				<li class="mui-table-view-cell">
					<a href="javascript:void(0)" class="mui-navigate-right" id="showMap">
						<div class="addbox">
							<div style="font-size: 1.2rem;"><b>{{ data['jobinfo']['address'] }}{{ data['jobinfo']['roomno'] }}</b></div>
							<div>{{ data['jobinfo']['province'] }}{{ data['jobinfo']['city'] }}{{ data['jobinfo']['district'] }}</div>
						</div>
						<input type="hidden" value="{{ data['jobinfo']['lng'] }}" id="lng">
						<input type="hidden" value="{{ data['jobinfo']['lat'] }}" id="lat">
					</a>
				</li>
			</ul>
		</div>
		<div id="leader">
			<ul class="mui-table-view">
				<li class="mui-table-view-cell">
					<!-- <a class="mui-navigate-right"> -->
					<a href="javascript:void(0)">
						<div class="imgbox left">
							<img src="{{ data['jobuserinfo']['headimgurl'] }}" class="auto-center">
						</div>
						<div class="infos left">
							<div class="ltc"><span>{{ data['jobinfo']['real_name'] }}</span>{{ data['jobinfo']['company_name'] }}</div>
							<!-- <div><span class="score">4.8</span>50人评价</div> -->
						</div>
					</a>
				</li>
			</ul>
		</div>
		<div id="tips">
			<p>防骗提示：若用人单位要求交费或押金，请提高警惕，并第一时间向我们微信后台举报！<a href="javascript:void(0)" class="tips none">去投诉</a></p>
		</div>
		<br>
		<br>
		<br>
		<br>
		<footer>
			<a href="#" class="collect none">收藏</a>
			<a href="javascript:void(0)" class="sign" id="SignJob" data-id="{{ data['jobinfo']['id'] }}">立即报名</a>
		</footer>
		<!-- <footer>
			<a href="javascript:void(0)" class="share">分享</a>
			<a href="/job/index" class="collect">更多兼职</a>
			<a href="javascript:void(0)" class="sign" id="SignJob" data-id="{{ data['jobinfo']['id'] }}">立即报名</a>
		</footer> -->
	</div>
</div>

<div id="detailAD" class="none">
	<img src="/public/img/bannerbottom.jpg">
	<div class="closead">
		<span class="mui-icon mui-icon-close auto-center"></span>
	</div>
</div>

<div id="Bind" class="alert none">
	<h3>绑定手机</h3>
	<br>
	<p>您尚未绑定手机，绑定后将获得更好的体验哦</p>
	<div id="nobind" class="resu" style="padding:0;">
		<div class="mui-input-row">
			<label>手机号</label>
			<input type="text" placeholder="请输入您的手机号" id="telphone">
		</div>
		<div class="mui-input-row">
			<input type="number" name="captcha" placeholder="请输入短信验证码" id="captcha">
			<button class="getcaptcha">获取验证码</button>
			<button class="waiting none"></button>
		</div>
	</div>
	<button class="footbtn" id="TelBind">绑定</button>
</div>

<div id="ResumeB" class="alert none">
	<h3>个人简历</h3>
	<br>
	<p>请填写您的最基本资料，以获得快速投递简历的机会</p>
	<p>更详细的资料请在个人中心填写</p>
	<div id="resume" class="resu" style="padding:0;">
		<div class="mui-input-row">
			<label>姓名</label>
			<input type="text" placeholder="请输入您的真实姓名" id="userName" value="{{ data['userinfo']['real_name'] }}">
		</div>
		<div class="mui-input-row">
			<label>性别</label>
			<input type="text" placeholder="请选择您的性别" id="changeUserSex" value="{{ data['userinfo']['sex'] }}" readonly="readonly">
		</div>
		<div class="mui-input-row">
			<label>生日</label>
			<input type="text" data-options='{"type":"date","beginYear":1960,"endYear":2016}' value="{{ data['userinfo']['birth'] }}" id="userBirthday" placeholder="请选择您的生日" readonly="readonly">
		</div>
		<div class="mui-input-row">
			<label>身份</label>
			<input type="text" placeholder="请输入您的身份" value="{{ data['userinfo']['identity'] }}" id="userIdentity">
		</div>
		<div class="mui-input-row">
			<label>学历</label>
			<input type="text" placeholder="请选择您的学历" id="userDegree" value="{{ data['userinfo']['education'] }}" readonly="readonly">
		</div>
		<div class="mui-input-row">
			<label>工作经验</label>
			<input type="text" placeholder="请选择工作经验" id="userJobyear" value="{{ data['userinfo']['experience'] }}" readonly="readonly">
		</div>
		<div class="mui-input-row">
			<label>工作领域</label>
			<input type="text" placeholder="请选择工作领域" id="userJobfield" value="{{ data['userinfo']['workarea'] }}" readonly="readonly">
		</div>
	</div>
	<button id="Push" class="footbtn">保存简历</button>
</div>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script type="text/javascript">

	//mui.init({
		// beforeback: function(){
		// 	var his = window.history.back();
		// 	console.log(his)
		// 	return false;
		// }
	//});
	
	$("#detailAD .closead").on('tap',function(){
		$("#detailAD").remove();
		$('footer').css("height","3rem");
		var date = new Date();
		date.setTime(date.getTime()+60*60*24*3*1000);
		$.cookie('showAD2', 1, {expires: date});
	});

	$(function(){
		if($.cookie('showAD2') > 0){
			$('footer').css("height","3rem");
		} else {
			$("#detailAD").show();
		}
	});

	$(".backtoindex").on('tap',function(){
		var his = window.history;
		console.log(his.length)
		if(his.length == 1){
			window.location.href = '/job/index';
		} else {
			window.history.back();
		}
	})

	wx.config({  
	    debug: false, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。  
	    appId: '{{ sign['appId'] }}', // 必填，公众号的唯一标识  
	    timestamp: {{ sign['timestamp'] }}, // 必填，生成签名的时间戳  
	    nonceStr: '{{ sign['nonceStr'] }}', // 必填，生成签名的随机串  
	    signature: '{{ sign['signature'] }}',// 必填，签名，见附录1  
	    jsApiList: [
	    	'openLocation',
	    	'onMenuShareAppMessage',
	    	'onMenuShareTimeline'
	    ] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2  
	});

	var indexA;
	var indexB;

	function showBindTel(){
		indexA = layer.open({
			type: 1,
			title:false,
			closeBtn:true,
			content: $("#Bind"),
			area: ['90%', 'auto'],
			shadeClose: false,
			time:0
		});
	}

	function showInnelResume(){
		indexB = layer.open({
			type: 1,
			title:false,
			closeBtn:true,
			content: $("#ResumeB"),
			area: ['90%', 'auto'],
			shadeClose: false,
			time:0
		});
	}

	wx.ready(function () {
		document.querySelector('#showMap').onclick = function () {
			var Glng = Number($('#lng').val());
			var Glat = Number($('#lat').val());
			var Gaddress = "{{ data['jobinfo']['province'] }}"+"{{ data['jobinfo']['city'] }}"+"{{ data['jobinfo']['district'] }}";
			var Gname = "{{ data['jobinfo']['address'] }}"+"{{ data['jobinfo']['roomno'] }}";

			wx.openLocation({
			    latitude: Glat,
			    longitude: Glng,
			    name: Gname,
			    address: Gaddress,
			    scale: 14,
			    infoUrl: 'http://weixin.qq.com'
		    });
		}

		wx.onMenuShareAppMessage({
            title: "{{ data['jobinfo']['title'] }}"+'-'+"{{ data['jobinfo']['salary'] }}元/{{ data['jobinfo']['salary_type'] }}"+'-工资'+"{{ data['jobinfo']['salary_time'] }}", // 分享标题
            desc: "{{ data['jobinfo']['content3'] }}", // 分享描述
            link: window.location.href, // 分享链接，该链接域名或路径必须与当前页面对应的公众号JS安全域名一致
            imgUrl: 'http://www.ijztt.com/public/img/aboutus.png', // 自定义图标
            type: 'link', // 分享类型,music、video或link，不填默认为link
            dataUrl: '', // 如果type是music或video，则要提供数据链接，默认为空
            success: function () {
                // 用户确认分享后执行的回调函数
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
            }
        });

        wx.onMenuShareTimeline({
			//title: '兼职头条-招聘-'+"{{ data['jobinfo']['title'] }}",
			title: "{{ data['jobinfo']['title'] }}"+'-'+"{{ data['jobinfo']['salary'] }}元/{{ data['jobinfo']['salary_type'] }}"+'-工资'+"{{ data['jobinfo']['salary_time'] }}",
			link: window.location.href,
			imgUrl: 'http://www.ijztt.com/public/img/aboutus.png',
			trigger: function (res) {
			// 不要尝试在trigger中使用ajax异步请求修改本次分享的内容，因为客户端分享操作是一个同步操作，这时候使用ajax的回包会还没有返回
			//alert('用户点击发送给朋友');
			},
			success: function (res) {
			//alert('已分享');
			},
			cancel: function (res) {
			//alert('已取消');
			},
			fail: function (res) {
			//alert(JSON.stringify(res));
			}
	    });

	})

	$(".share").on('tap',function(){
		$("#mask").show();
	});

	$("#mask").on('tap',function(){
		$(this).hide();
	});

	$('.getcaptcha').on('tap',function(){
		var mobile = $("#telphone").val();
		if(mobile.length == ''){
	        layer.msg('请填写手机号。');
	        return false;
	    }
		if(mobile.length != 11){
	        layer.msg('手机号长度不正确。');
	        return false;
	    }
	    if(!checkMobile(mobile)){
	    	layer.msg('请输入正确的手机号。');
        	return false;
        }

        $(this).attr('disabled','disabled');
        $.get('/job/getphonecode',{'mobile':mobile},function(data){
			if(data.error_code == '0'){
				mobileMsg();
			} else {
				layer.msg(data.reason);
			}
		},'json');
	});

	$("#TelBind").on('tap',function(){
		var mobile = $("#telphone").val();
		if(mobile.length == ''){
	        layer.msg('请填写手机号。');
	        return false;
	    }
		if(mobile.length != 11){
	        layer.msg('手机号长度不正确。');
	        return false;
	    }
	    if(!checkMobile(mobile)){
	    	layer.msg('请输入正确的手机号。');
        	return false;
        }

		var captcha = $("#captcha").val();
		if(captcha.length == ''){
	        layer.msg('请填写验证码。');
	        return false;
	    }

	    $(this).attr('disabled','disabled');
	    $.get('/job/edituserinfo',{'mobile':mobile,'vcode':captcha},function(data){
			if(data.error_code == '0'){
				layer.msg('绑定成功！');
				layer.close(indexA);
			} else {
				layer.msg(data.reason);
			}
		},'json');
	});

	$("#SignJob").on("tap",function(){

		var id = $(this).attr('data-id');

		indexload = layer.load(2, {
		  shade: [0.4,'#000'] //0.1透明度的白色背景
		});

		$.get('/job/checkdata',function(data){
			console.log(data);
			if(data.error_code != '0'){
				layer.close(indexload);
				if(data.reason == "no phone"){	
					showBindTel();
					layer.msg("请先绑定个人手机哦~",{time:3000});
				}
				if(data.reason == "no other"){
					showInnelResume();
					layer.msg("请先填写个人简历哦~",{time:3000});
				}
			} else {
				$.get('/job/apply',{'jobid':id},function(data){
					if(data.error_code == '0'){
						layer.close(indexload);
						var href = '/job/signdone?applyid='+data.result.apply_id;
						layer.msg("报名成功！");
						setTimeout("window.location.href='" + href + "'",1000);
					} else {
						layer.close(indexload);
						layer.msg("您已报名过该工作。");
					}
				},'json')
			}
		},'json');
	});

	$("#Push").on('tap',function(){

		var real_name = $("#userName").val();
		if(real_name.length == ''){
	        layer.msg('请填写姓名。');
	        return false;
	    }
	    if(!checkName(real_name)){
	    	layer.msg('请填写真实姓名。');
        	return false;
        }

        var sex = $("#changeUserSex").val();
        if(sex.length == ''){
	        layer.msg('请选择性别。');
	        return false;
	    }

	    var birth = $("#userBirthday").val();
        if(birth.length == ''){
	        layer.msg('请选择生日。');
	        return false;
	    }

	    var birth = $("#userBirthday").val();
        if(birth.length == ''){
	        layer.msg('请选择生日。');
	        return false;
	    }

	    var identity = $("#userIdentity").val();
        if(identity.length == ''){
	        layer.msg('请填写身份。');
	        return false;
	    }

	    var education = $("#userDegree").val();
        if(education.length == ''){
	        layer.msg('请选择学历。');
	        return false;
	    }

	    var experience = $("#userJobyear").val();
        if(experience.length == ''){
	        layer.msg('请选择工作经验。');
	        return false;
	    }

	    var workarea = $("#userJobfield").val();
        if(workarea.length == ''){
	        layer.msg('请选择工作领域。');
	        return false;
	    }

	    indexload = layer.load(2, {
		  shade: [0.4,'#000'] //0.1透明度的白色背景
		});

	    $.get("/job/editresume",{
	    	"real_name":real_name,
	    	"sex":sex,
	    	"birth":birth,
	    	"identity":identity,
	    	"education":education,
	    	"experience":experience,
	    	"workarea":workarea
	    },function(data){
	    	if(data.error_code == '0'){
	    		layer.close(indexB);
	    		layer.close(indexload);
				layer.msg('简历提交成功！您可以报名工作了~',{time:3000});
			} else {
				layer.close(indexload);
				layer.msg(data.reason);
			}
	    },'json')

	});

</script>

{% endblock %}
{% block footer %}
       
{% endblock %}