{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职之家 - 首页{% endblock %}

{% block content %}
<style type="text/css">

	
</style>


<!-- <header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">首页</h1>
</header> -->

<div class="mui-content">
	<div id="search">
		<div>
			<div class="select left mui-collapse">
				<a class="mui-navigate-right selections" href="#" data-type="city">深圳</a>
			</div>
			<div class="mui-input-group left">
				<div class="mui-input-row">
					<label><span class="mui-icon mui-icon-search"></span></label>
					<input type="text" class="mui-input-clear" placeholder="学生" data-input-clear="5">
					<button class="right">搜索</button>
				</div>
			</div>
			<div class="user left">
				<a href="/job/user"><span class="mui-icon mui-icon-contact"></span></a>
			</div>
			<div class="selectbox none" data-select="city">
				<div class="container">
					<h5>选择城市</h5>
					<div class="row">
						<div class="col-xs-4"><a href="#" class="active">全部</a></div>
					</div>
					<div class="row">
						<div class="col-xs-4"><a href="#">广州</a></div>
						<div class="col-xs-4"><a href="#">深圳</a></div>
						<div class="col-xs-4"><a href="#">东莞</a></div>
						<div class="col-xs-4"><a href="#">惠州</a></div>
						<div class="col-xs-4"><a href="#">那美克星</a></div>
						<div class="col-xs-4"><a href="#">上海</a></div>
						<div class="col-xs-4"><a href="#">北京</a></div>
						<div class="col-xs-4"><a href="#">成都</a></div>
						<div class="col-xs-4"><a href="#">重庆</a></div>
						<div class="col-xs-4"><a href="#">伊斯坦布尔</a></div>
						<div class="col-xs-4"><a href="#">乌鲁木齐</a></div>
						<div class="col-xs-4"><a href="#">玛丽娜斯</a></div>
						<div class="col-xs-4"><a href="#">西安</a></div>
						<div class="col-xs-4"><a href="#">武汉</a></div>
						<div class="col-xs-4"><a href="#">麦哲伦星云</a></div>
						<div class="col-xs-4"><a href="#">准噶尔</a></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="slider" class="mui-slider">
		<div class="mui-slider-group mui-slider-loop">
			<!-- 额外增加的一个节点(循环轮播：第一个节点是最后一张轮播) -->
			<div class="mui-slider-item mui-slider-item-duplicate">
				<a href="#">
					<img src="/public/img/indexbg1.jpg" class="auto-center">
				</a>
			</div>
			<!-- 第一张 -->
			<div class="mui-slider-item">
				<a href="#">
					<img src="/public/img/indexbg1.jpg" class="auto-center">
				</a>
			</div>
			<!-- 第二张 -->
			<div class="mui-slider-item">
				<a href="#">
					<img src="/public/img/indexbg1.jpg" class="auto-center">
				</a>
			</div>
			<!-- 第三张 -->
			<div class="mui-slider-item">
				<a href="#">
					<img src="/public/img/indexbg1.jpg" class="auto-center">
				</a>
			</div>
			<!-- 额外增加的一个节点(循环轮播：最后一个节点是第一张轮播) -->
			<div class="mui-slider-item mui-slider-item-duplicate">
				<a href="#">
					<img src="/public/img/indexbg1.jpg" class="auto-center">
				</a>
			</div>
		</div>
		<div class="mui-slider-indicator">
			<div class="mui-indicator mui-active"></div>
			<div class="mui-indicator"></div>
			<div class="mui-indicator"></div>
		</div>
	</div>
	<div id="selection" class="container">
		<div class="row">
			<div class="col-xs-3 mui-collapse">
				<a class="mui-navigate-right selections" data-type="address">全部</a>
			</div>
			<div class="col-xs-3 mui-collapse">
				<a class="mui-navigate-right selections" data-type="type">类型</a>
			</div>
			<div class="col-xs-3 mui-collapse">
				<a class="mui-navigate-right selections" data-type="condition">筛选</a>
			</div>
			<div class="col-xs-3 mui-collapse">
				<a class="mui-navigate-right selections" data-type="sort">排序</a>
			</div>
		</div>
		<div class="selectbox none" data-select="address">
			<div class="container">
				<h5>选择地区</h5>
				<div class="row">
					<div class="col-xs-4"><a href="#" class="active">全部</a></div>
				</div>
				<div class="row">
					<div class="col-xs-4"><a href="#">深圳</a></div>
					<div class="col-xs-4"><a href="#">深圳</a></div>
					<div class="col-xs-4"><a href="#">深圳</a></div>
					<div class="col-xs-4"><a href="#">深圳</a></div>
					<div class="col-xs-4"><a href="#">深圳</a></div>
					<div class="col-xs-4"><a href="#">深圳</a></div>
				</div>
			</div>
		</div>
		<div class="selectbox none" data-select="type">
			<div class="container">
				<h5>职位类型</h5>
				<div class="row">
					<div class="col-xs-4"><a href="#" class="active">全部</a></div>
				</div>
				<div class="row">
					<div class="col-xs-4"><a href="#">送餐员</a></div>
					<div class="col-xs-4"><a href="#">安保</a></div>
					<div class="col-xs-4"><a href="#">促销</a></div>
					<div class="col-xs-4"><a href="#">礼仪</a></div>
					<div class="col-xs-4"><a href="#">核弹打蜡</a></div>
					<div class="col-xs-4"><a href="#">临时工</a></div>
					<div class="col-xs-4"><a href="#">校内</a></div>
					<div class="col-xs-4"><a href="#">服务员</a></div>
					<div class="col-xs-4"><a href="#">设计</a></div>
					<div class="col-xs-4"><a href="#">编程</a></div>
					<div class="col-xs-4"><a href="#">派单</a></div>
					<div class="col-xs-4"><a href="#">航母维修</a></div>
					<div class="col-xs-4"><a href="#">家教</a></div>
					<div class="col-xs-4"><a href="#">打酱油</a></div>
					<div class="col-xs-4"><a href="#">客服</a></div>
					<div class="col-xs-4"><a href="#">翻译</a></div>
					<div class="col-xs-4"><a href="#">模特</a></div>
					<div class="col-xs-4"><a href="#">快递</a></div>
					<div class="col-xs-4"><a href="#">抢银行</a></div>
				</div>
			</div>
		</div>
		<div class="selectbox none" data-select="condition">
			<div class="container">
				<h5>时间要求</h5>
				<div class="row">
					<div class="col-xs-4"><a href="#" class="active">都可</a></div>
					<div class="col-xs-4"><a href="#">长期兼职</a></div>
					<div class="col-xs-4"><a href="#">短期兼职</a></div>
				</div>
				<h5>性别要求</h5>
				<div class="row">
					<div class="col-xs-4"><a href="#" class="active">全部</a></div>
					<div class="col-xs-4"><a href="#">男生</a></div>
					<div class="col-xs-4"><a href="#">女生</a></div>
				</div>
				<h5>身份要求</h5>
				<div class="row">
					<div class="col-xs-4"><a href="#" class="active">全部</a></div>
					<div class="col-xs-4"><a href="#">学生可做</a></div>
					<div class="col-xs-4"><a href="#">非学生可做</a></div>
				</div>
				<h5>结算方式</h5>
				<div class="row">
					<div class="col-xs-4"><a href="#" class="active">不限</a></div>
					<div class="col-xs-4"><a href="#">日结</a></div>
					<div class="col-xs-4"><a href="#">周末结算</a></div>
					<div class="col-xs-4"><a href="#">月底结算</a></div>
				</div>
			</div>
		</div>
		<div class="selectbox none" data-select="sort">
			<div class="container">
				<div class="row">
					<br>
					<div class="col-xs-12"><a href="#" class="active">默认排序</a></div>
					<div class="col-xs-12"><a href="#">离我最近</a></div>
					<div class="col-xs-12"><a href="#">最新发布</a></div>
					<div class="col-xs-12"><a href="#">人气</a></div>
					<div class="col-xs-12"><a href="#">薪资</a></div>
				</div>
			</div>
		</div>
	</div>
	<ul class="mui-table-view joblist">
		<li class="mui-table-view-cell lists">
			<a href="detail">
				<h4>百货促销员兼陈列扫地倒垃圾我不信有这么长</h4>
				<div><span class="place">南山</span><span class="time">4.01 - 4.03</span></div>
				<div><span class="price">130元/天</span><span class="pricetype">日结</span></div>
				<span class="range">300m</span>
			</a>
		</li>
		<li class="mui-table-view-cell lists">
			<a href="detail">
				<h4>百货促销员兼陈列扫地倒垃圾</h4>
				<div><span class="place">南山</span><span class="time">4.01 - 4.03</span></div>
				<div><span class="price">130元/天</span><span class="pricetype">周末结算</span></div>
				<span class="range">300m</span>
			</a>
		</li>
		<li class="mui-table-view-cell lists">
			<a href="detail">
				<h4>百货促销员兼陈列扫地倒垃圾</h4>
				<div><span class="place">南山</span><span class="time">4.01 - 4.03</span></div>
				<div><span class="price">130元/天</span><span class="pricetype">月底结算</span></div>
				<span class="range">300m</span>
			</a>
		</li>
	</ul>
</div>

<div id="Bind" class="alert none">
	<h3>绑定手机</h3>
	<br>
	<p>您尚未绑定手机，绑定后将获得更好的体验哦</p>
	<div id="nobind" class="resu" style="padding:0;">
		<div class="mui-input-row">
			<label>手机号</label>
			<input type="text" placeholder="请输入您的手机号">
		</div>
		<div class="mui-input-row">
			<input type="text" placeholder="请输入短信验证码">
			<button>获取验证码</button>
		</div>
	</div>
	<button class="footbtn" id="TelBind">绑定</button>
</div>

<div id="ResumeB" class="alert none">
	<h3>简易简历</h3>
	<br>
	<p>请填写您的最基本资料，以获得快速投递简历的机会</p>
	<p>更详细的资料请在个人中心填写</p>
	<div id="resume" class="resu" style="padding:0;">
		<div class="mui-input-row">
			<label>姓名</label>
			<input type="text" placeholder="请输入您的真实姓名" id="userName">
		</div>
		<div class="mui-input-row">
			<label>性别</label>
			<input type="text" placeholder="请选择您的性别" id="changeUserSex" value="">
		</div>
		<div class="mui-input-row">
			<label>生日</label>
			<input type="text" data-options='{"type":"date","beginYear":1960,"endYear":2016}' value="" id="userBirthday" placeholder="请选择您的生日">
		</div>
		<div class="mui-input-row">
			<label>工作经验</label>
			<input type="text" placeholder="请选择工作经验" id="userJobyear" value="">
		</div>
	</div>
	<button id="Push" class="footbtn">保存简历</button>
</div>

<script src="/public/js/city.data.js" charset="utf-8"></script>
<script src="/public/js/city.data-3.js" charset="utf-8"></script>
<script type="text/javascript">

	mui.init();
	var slider = mui("#slider");
	slider.slider({
		interval: 3000
	});

	var indexA;
	var indexB;

	$(function(){

		indexA = layer.open({
			type: 1,
			title:false,
			closeBtn:true,
			content: $("#Bind"),
			area: ['90%', 'auto'],
			shadeClose: false,
			time:0
		});

	});

	$(".selections").on('tap',function(){
		var type = $(this).attr('data-type');
		if($(this).hasClass('active')){
			$(this).removeClass('active');
			$("[data-select = '"+type+"']").hide();
		} else {
			$(".selections").removeClass('active');
			$(this).addClass('active');
			$(".selections").each(function(){
				$('.selectbox').hide();
				$("[data-select = '"+type+"']").show();
			});
		}
	});

	$("#TelBind").on('tap',function(){
		layer.close(indexA);
		indexB = layer.open({
			type: 1,
			title:false,
			closeBtn:true,
			content: $("#ResumeB"),
			area: ['90%', 'auto'],
			shadeClose: false,
			time:0
		});
	});

</script>


{% endblock %}
{% block footer %}
       
{% endblock %}