{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 首页{% endblock %}

{% block content %}
<style type="text/css">
	
	
</style>


<!-- <header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">首页</h1>
</header> -->

<div class="mui-content">
	<div id="search">
		<div>
			<div class="select left mui-collapse">
				<a class="mui-navigate-right selections" href="javascript:void(0)" data-type="city" id="Selections">深圳</a>
			</div>
			<div class="mui-input-group left">
				<div class="mui-input-row">
					<label><span class="mui-icon mui-icon-search"></span></label>
					<input type="text" class="mui-input-clear" placeholder="学生" data-input-clear="5" id="SearchText">
					<button class="right" id="Search">搜索</button>
				</div>
			</div>
			<div class="user left">
				<a href="/job/user"><span class="mui-icon mui-icon-contact"></span></a>
			</div>
			<div class="selectbox none" data-select="city">
				<div class="container">
					<h5>当前城市</h5>
					<div class="row">
						<div class="col-xs-4"><a href="javascript:void(0)" id="nowcity"></a></div>
					</div>
					<h5>选择城市</h5>
					<div class="row citys">
						<div class="col-xs-4"><a href="/job/index?city=广州市" data-city="广州" data-province="440000" data-cityid="440100">广州</a></div>
						<div class="col-xs-4"><a href="/job/index?city=深圳市" data-city="深圳" data-province="440000" data-cityid="440300">深圳</a></div>
						<div class="col-xs-4"><a href="/job/index?city=东莞市" data-city="东莞" data-province="440000" data-cityid="441900">东莞</a></div>
						<!-- <div class="col-xs-4"><a href="/job/index?city=huizhou" data-city="huizhou" data-code="301">惠州</a></div>
						<div class="col-xs-4"><a href="/job/index?city=shanghai" data-city="shanghai" data-code="289">上海</a></div>
						<div class="col-xs-4"><a href="/job/index?city=beijing" data-city="beijing" data-code="131">北京</a></div>
						<div class="col-xs-4"><a href="/job/index?city=chengdu" data-city="chengdu" data-code="75">成都</a></div>
						<div class="col-xs-4"><a href="/job/index?city=chongqing" data-city="chongqing" data-code="132">重庆</a></div>
						<div class="col-xs-4"><a href="/job/index?city=xian" data-city="xian" data-code="233">西安</a></div>
						<div class="col-xs-4"><a href="/job/index?city=wuhan" data-city="wuhan" data-code="218">武汉</a></div> -->
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- <div style="position: relative;top:40px;">
		<button id="getLocation">获取</button>
		<span id="lng"></span>      
		<span id="lat"></span>
	</div> -->

	<div id="slider" class="mui-slider">
		<div class="mui-slider-group mui-slider-loop">
			<!-- 额外增加的一个节点(循环轮播：第一个节点是最后一张轮播) -->
			<div class="mui-slider-item mui-slider-item-duplicate">
				<a href="http://www.jobchain.us/db/index">
					<img src="/public/img/banner33.jpg" class="auto-center">
				</a>
			</div>
			<!-- 第一张 -->
			<div class="mui-slider-item">
				<a href="http://www.jobchain.us/db/index">
					<img src="/public/img/banner11.jpg" class="auto-center">
				</a>
			</div>
			<!-- 第二张 -->
			<div class="mui-slider-item">
				<a href="http://www.jobchain.us/db/index">
					<img src="/public/img/banner22.jpg" class="auto-center">
				</a>
			</div>
			<!-- 第三张 -->
			<div class="mui-slider-item">
				<a href="http://www.jobchain.us/db/index">
					<img src="/public/img/banner33.jpg" class="auto-center">
				</a>
			</div>
			<!-- 额外增加的一个节点(循环轮播：最后一个节点是第一张轮播) -->
			<div class="mui-slider-item mui-slider-item-duplicate">
				<a href="http://www.jobchain.us/db/index">
					<img src="/public/img/banner11.jpg" class="auto-center">
				</a>
			</div>
		</div>
		<div class="mui-slider-indicator">
			<div class="mui-indicator mui-active"></div>
			<div class="mui-indicator"></div>
			<div class="mui-indicator"></div>
		</div>
	</div>
	<div id="selection" class="container">
		<div class="row">
			<div class="col-xs-3 mui-collapse">
				<a class="mui-navigate-right selections" data-type="address" id="Address">地区</a>
			</div>
			<div class="col-xs-3 mui-collapse">
				<a class="mui-navigate-right selections" data-type="type" id="Type">类型</a>
			</div>
			<div class="col-xs-3 mui-collapse">
				<a class="mui-navigate-right selections" data-type="condition" id="Condition">性别</a>
			</div>
			<div class="col-xs-3 mui-collapse">
				<a class="mui-navigate-right selections" data-type="sort" id="Sort">默认排序</a>
			</div>
		</div>
		<div class="selectbox none" data-select="address">
			<div class="container Gaddresses">
				<h5>选择地区</h5>
				<div class="row">
					<div class="col-xs-4"><a href="javascript:void(0)" class="active" id="alladdress" data-district=''>全部</a></div>
				</div>
				<div class="row addresses">
					<div class="col-xs-4"><a href="javascript:void(0)" data-district="罗湖区">罗湖区</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-district="福田区">福田区</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-district="南山区">南山区</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-district="宝安区">宝安区</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-district="龙岗区">龙岗区</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-district="盐田区">盐田区</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-district="光明新区">光明新区</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-district="坪山新区">坪山新区</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-district="龙华新区">龙华新区</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-district="大鹏新区">大鹏新区</a></div>
				</div>
			</div>
		</div>
		<div class="selectbox none" data-select="type">
			<div class="container Gtypes">
				<h5>职位类型</h5>
				<div class="row">
					<div class="col-xs-4"><a href="javascript:void(0)" class="active" id="alltype" data-type="">全部</a></div>
				</div>
				<div class="row types">
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='传单派发'>传单派发</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='促销导购'>促销导购</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='地推拉访'>地推拉访</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='商品代理'>商品代理</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='网赚试玩'>网赚试玩</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-type="核弹打蜡">核弹打蜡</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-type="编程">编程</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-type="航母维修">航母维修</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-type="打酱油">打酱油</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-type="快递">快递</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-type="抢银行">抢银行</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='调研'>调研</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='送餐员'>送餐员</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='促销'>促销</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='礼仪'>礼仪</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='安保'>安保</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='销售'>销售</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='服务员'>服务员</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='临时工'>临时工</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='校内'>校内</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='设计'>设计</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='文员'>文员</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='派单'>派单</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='模特'>模特</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='实习'>实习</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='家教'>家教</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='演出'>演出</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='客服'>客服</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='翻译'>翻译</a></div>
					<div class='col-xs-4'><a href='javascript:void(0)' data-type='其他'>其他</a></div>
				</div>
			</div>
		</div>
		<div class="selectbox none" data-select="condition">
			<div class="container">
				<!-- <h5>时间要求</h5>
				<div class="row">
					<div class="col-xs-4"><a href="javascript:void(0)" class="active">都可</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)">长期兼职</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)">短期兼职</a></div>
				</div> -->
				<h5>性别要求</h5>
				<div class="row sexs">
					<div class="col-xs-4"><a href="javascript:void(0)" class="active" data-sex="">全部</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-sex="男">男生</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-sex="女">女生</a></div>
				</div>
				<!-- <h5>身份要求</h5>
				<div class="row">
					<div class="col-xs-4"><a href="javascript:void(0)" class="active">全部</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)">学生可做</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)">非学生可做</a></div>
				</div> -->
				<!-- <h5>结算方式</h5>
				<div class="row salarys">
					<div class="col-xs-4"><a href="javascript:void(0)" class="active" data-salary="">不限</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-salary="日结">日结</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-salary="周结">周结</a></div>
					<div class="col-xs-4"><a href="javascript:void(0)" data-salary="月结">月结</a></div>
				</div> -->
			</div>
		</div>
		<div class="selectbox none" data-select="sort">
			<div class="container">
				<div class="row sorts">
					<br>
					<div class="col-xs-12"><a href="javascript:void(0)" class="active" data-order="create_time">默认排序</a></div>
					<div class="col-xs-12"><a href="javascript:void(0)" data-order="juli">离我最近</a></div>
					<div class="col-xs-12 none"><a href="javascript:void(0)">最新发布</a></div>
					<div class="col-xs-12"><a href="javascript:void(0)" data-order="view_num">人气</a></div>
					<div class="col-xs-12 none"><a href="javascript:void(0)">薪资</a></div>
				</div>
			</div>
		</div>
	</div>
	<ul class="mui-table-view joblist" id="Joblist">
		<!-- <li class='mui-table-view-cell lists'>
			<a href='detail?jobid={{ item['id'] }}'>
				<h4>百货促销员兼陈列扫地倒垃圾我不信有这么长</h4>
				<div><span class='place'>南山</span><span class='time'>4.01 - 4.03</span></div>
				<div><span class='price'>130元/天</span><span class='pricetype'>日结</span></div>
				<span class='range'>300m</span>
			</a>
		</li>
		<li class="mui-table-view-cell lists">
			<a href="detail">
				<h4>百货促销员兼陈列扫地倒垃圾</h4>
				<div><span class="place">南山</span><span class="time">4.01 - 4.03</span></div>
				<div><span class="price">130元/天</span><span class="pricetype">周末结算</span></div>
				<span class="range">300m</span>
			</a>
		</li>
		<li class="mui-table-view-cell lists">
			<a href="detail">
				<h4>百货促销员兼陈列扫地倒垃圾</h4>
				<div><span class="place">南山</span><span class="time">4.01 - 4.03</span></div>
				<div><span class="price">130元/天</span><span class="pricetype">月底结算</span></div>
				<span class="range">300m</span>
			</a>
		</li> -->
	</ul>
</div>

<!-- <div id="Bind" class="alert none">
	<h3>绑定手机</h3>
	<br>
	<p>您尚未绑定手机，绑定后将获得更好的体验哦</p>
	<div id="nobind" class="resu" style="padding:0;">
		<div class="mui-input-row">
			<label>手机号</label>
			<input type="text" placeholder="请输入您的手机号" id="telphone">
		</div>
		<div class="mui-input-row">
			<input type="number" name="captcha" placeholder="请输入短信验证码" id="captcha">
			<button class="getcaptcha">获取验证码</button>
			<button class="waiting none"></button>
		</div>
	</div>
	<button class="footbtn" id="TelBind">绑定</button>
</div>

<div id="ResumeB" class="alert none">
	<h3>简易简历</h3>
	<br>
	<p>请填写您的最基本资料，以获得快速投递简历的机会</p>
	<p>更详细的资料请在个人中心填写</p>
	<div id="resume" class="resu" style="padding:0;">
		<div class="mui-input-row">
			<label>姓名</label>
			<input type="text" placeholder="请输入您的真实姓名" id="userName">
		</div>
		<div class="mui-input-row">
			<label>性别</label>
			<input type="text" placeholder="请选择您的性别" id="changeUserSex" value="">
		</div>
		<div class="mui-input-row">
			<label>生日</label>
			<input type="text" data-options='{"type":"date","beginYear":1960,"endYear":2016}' value="" id="userBirthday" placeholder="请选择您的生日">
		</div>
		<div class="mui-input-row">
			<label>工作经验</label>
			<input type="text" placeholder="请选择工作经验" id="userJobyear" value="">
		</div>
	</div>
	<button id="Push" class="footbtn">保存简历</button>
</div> -->

<div id="allmap"></div>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=36O14NhaK4ciWsoaG3xgNnngT29wiEpB"></script>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script type="text/javascript">

	mui.init();
	var slider = mui("#slider");
	slider.slider({
		interval: 3000
	});

	wx.config({  
	    debug: false, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。  
	    appId: '{{ sign['appId'] }}', // 必填，公众号的唯一标识  
	    timestamp: {{ sign['timestamp'] }}, // 必填，生成签名的时间戳  
	    nonceStr: '{{ sign['nonceStr'] }}', // 必填，生成签名的随机串  
	    signature: '{{ sign['signature'] }}',// 必填，签名，见附录1  
	    jsApiList: [
	    	'getLocation'
	    ] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2  
	});

	var indexA;
	var indexB;

	wx.ready(function(){
		wx.getLocation({
			dataType:"json",
			success: function (res) {
				var lng = res.longitude;
				var lat = res.latitude;
				var date = new Date();
				date.setTime(date.getTime()+60*60*24*1*1000);
				$.cookie('lng', lng, {expires: date});
				$.cookie('lat', lat, {expires: date});
				//
				geocoder = new AMap.Geocoder({
		            city: ""//城市，默认：“全国”
		        });
		        //alert($.cookie('lng'))
		        var lnglatXY=[$.cookie('lng'), $.cookie('lat')];//地图上所标点的坐标
		        geocoder.getAddress(lnglatXY, function(status, result) {
		        	//alert(status)
		        	//alert(JSON.stringify(result))
		            if (status === 'complete' && result.info === 'OK') {
		                //获得了有效的地址信息:
		                //即，result.regeocode.formattedAddress
		                //console.log(result);
		                var city = result.regeocode.addressComponent.city;
		            }else{
		                var city = '深圳市';
		                //获取地址失败
		            }
		            $.cookie('city', city, {expires: date});
		            //alert($.cookie('city'));
		            var cityName = $.cookie('city');
		            nowCity = $.cookie('city');
					var arr = cityName.split('市');
					var losCity = arr[0];
					//alert(losCity)
					$("#nowcity").text(losCity).attr('href',"/job/index?city="+cityName+"").attr("data-city",losCity);
					star(losCity,cityName);
					//alert(window.location.href);
		        });
				//

			}
		});
		
	})

	// var map = new BMap.Map("allmap");
	// function myFun(result){
	// 	console.log(result)
	// 	//lng = result.center.lng;
	// 	//lat = result.center.lat;
	// 	var cityName = result.name;
	// 	nowCity = cityName;
	// 	var arr = cityName.split('市');
	// 	var losCity = arr[0];
	// 	console.log("当前定位城市:"+cityName);
	// 	$("#nowcity").text(losCity).attr('href',"/job/index?city="+cityName+"").attr("data-city",losCity);
	// 	//console.log(lng,lat)
	// 	//$("#lng").html(lng);
	// 	//$("#lat").html(lat);
	// 	star(losCity);
	// }
	// var myCity = new BMap.LocalCity();
	// myCity.get(myFun);

	// $(function(){
	// 	wx.getLocation({
	// 		success: function (res) {
	// 			//alert(res.latitude,res.longitude)
	// 			lng = res.longitude;
	// 			lat = res.latitude;
	// 			$("#lng").html(lng);
	// 			$("#lat").html(lat);
	// 			Selection('',nowCity,lng,lat);
	// 		}
	// 	});
	// });

	var keyword = '';
	var district = '';
	var type = '';
	var sex = '';
	var salary_time = '';
	var order = "create_time";
	var nowCity = '';

	function Selection(keyword,district,type,sex,salary_time,order,city,orderby){
		//alert(keyword+district+type+sex+salary_time+order+city);
		//alert($.cookie('lng'));
		//alert(city)
		
		indexload = layer.load(2, {
		  shade: [0.4,'#000'] //0.1透明度的白色背景
		});

		ordersc = "desc";
		if(orderby){
			ordersc = orderby;
		} else {
			ordersc = "desc";
		}
		
		$.post('/job/getjob',{
			"keyword":keyword,
			"city":nowCity ? nowCity : '深圳市',
			"lng":$.cookie('lng') ? $.cookie('lng') : 113.235486,
			"lat":$.cookie('lat') ? $.cookie('lat') : 22.619456,
			// "lng":113.235486,
			// "lat":22.619456,
			"district":district,
			"type":type,
			"sex":sex,
			"salary_time":salary_time,
			"order":order,
			"orderby":ordersc
		},function(data){
			if(data.error_code == '0'){
				$('#Joblist').empty();
				console.log(data.result)
				var len = data.result.length;
				if(len != 0){
					for(var i = 0; i < len; i++){
						var dom =   "<li class='mui-table-view-cell lists'>"
								+		"<a href='/job/detail?jobid="+data.result[i].id+"'>"
								+			"<h4>"+data.result[i].title+"</h4>"
								+			"<div><span class='place'>"+data.result[i].district+"</span><span class='time'>"+data.result[i].start_date+" - "+data.result[i].end_date+"</span><span style='color: #868686;'>共"+data.result[i].days+"天<span></div>"
								+			"<div><span class='price'>"+data.result[i].salary+"元/"+data.result[i].salary_type+"</span><span class='pricetype'>日结</span></div>"
								+			"<span class='range'>"+data.result[i].juli+"</span>"
								+		"</a>"
								+	"</li>";
						$('#Joblist').append(dom);
					}
				} else {
					$('#Joblist').append("<div class='noneshow'>暂无相关工作。</div>");
				}
				layer.close(indexload);
			} else {
				//alert('nonono')
				console.log(data.reason);
				layer.close(indexload);
			}
		},'json');
	}

	function star(cityName,cityAllName){
		// var urlArr = window.location.href.split('?');
		// var rulesA = urlArr[1];
		var rulesA = $_GET['city'];
		console.log(rulesA);
	    if(rulesA){
	    	var city = decodeURIComponent($_GET['city']);
	    	nowCity = city;
	    	var arr1 = city.split('市');
			var losCity = arr1[0];
			console.log(losCity);
	    } else {
	    	var city = cityAllName;
			nowCity = city;
			var losCity = cityName;
	    }
	    var hasCity = 0;
    	$(".citys a").each(function(){
    		var _this = $(this);
    		var data = _this.attr("data-city");
    		var text = _this.text();
    		console.log(losCity,data)
    		if(data == losCity){
    			//alert(data+losCity)
    			_this.addClass('active');
    			//alert('789')
    			// alert(cityName+losCity)
    			hasCity = 1;
    			var provinceid = _this.attr("data-province");
	    		var cityid = _this.attr("data-cityid");
	    		//alert(provinceid+cityid)
	    		$("#Selections").text(text);
	    		showCityList(provinceid,cityid);
	    		Selection(keyword,district,type,sex,salary_time,order,nowCity);
	    		if(cityName != losCity){
	    // 			var btnArray = ['取消', '切换'];
				 //    mui.confirm("您当前所在地区为"+cityName+"市，是否切换？", '切换城市', btnArray, function(e) {
					// 	if (e.index == 1) {
					// 		//$(".citys a[data-code='"+codA+"']").click();
					// 		window.location.href = $(".citys a[data-city='"+cityName+"']").attr('href');
					// 	} else {
					// 		$("#Selections").text(text);
			  //   			// showBindTel();
			  //   			showCityList(provinceid,cityid);
			  //   			Selection(keyword,district,type,sex,salary_time,order,city);
					// 	}
					// })				
					//checkdata();
	    		} else {
	    			$("#nowcity").addClass('active');
	    		}
    		}
    	});
    	if(hasCity == 0){
    		layer.msg('暂不支持该城市，即将跳转到深圳市。')
    		setTimeout("window.location.href = '/job/index?city=深圳市'",2000);
    	} 
	}

	function showCityList(province,city){
		$(".addresses").empty();
		var lenA = cityData.length;
		for(var i = 0;i < lenA; i++){
			if(cityData[i].id == province){
				var cityList = cityData[i].children;
				//console.log(cityList)
				var lenB = cityList.length;
				for(var j = 0; j < lenB; j++){
					if(cityList[j].id == city){
						var districtList = cityList[j].children;
						//console.log(districtList);
						var lenC = districtList.length;
						for(var k = 0; k < lenC; k++){
							//var district = districtList[k].text;
							//console.log(district);
							var dom = "<div class='col-xs-4'><a href='javascript:void(0)' data-district='"+districtList[k].text+"'>"+districtList[k].text+"</a></div>"
							$(".selectbox[data-select='address'] .addresses").append(dom);
						}
					}
				}
			}
		}
	}

	// function checkdata(){
	// 	$.get('/job/checkdata',function(data){
	// 		console.log(data);
	// 		if(data.error_code != '0'){
	// 			if(data.reason == "no phone"){
	// 				showBindTel();
	// 			}
	// 			if(data.reason == "no other"){
	// 				showInnelResume();
	// 			}
	// 		}
	// 	},'json');
	// }

	// function showBindTel(){
	// 	indexA = layer.open({
	// 		type: 1,
	// 		title:false,
	// 		closeBtn:true,
	// 		content: $("#Bind"),
	// 		area: ['90%', 'auto'],
	// 		shadeClose: false,
	// 		time:0
	// 	});
	// }

	// function showInnelResume(){
	// 	indexB = layer.open({
	// 		type: 1,
	// 		title:false,
	// 		closeBtn:true,
	// 		content: $("#ResumeB"),
	// 		area: ['90%', 'auto'],
	// 		shadeClose: false,
	// 		time:0
	// 	});
	// }

	$(".selections").on('tap',function(){
		var type = $(this).attr('data-type');
		if($(this).hasClass('active')){
			$(this).removeClass('active');
			$("[data-select = '"+type+"']").hide();
		} else {
			$(".selections").removeClass('active');
			$(this).addClass('active');
			$(".selections").each(function(){
				$('.selectbox').hide();
				$("[data-select = '"+type+"']").show();
			});
		}
	});

	$("#Search").on('tap',function(){
		keyword = $('#SearchText').val();
		Selection(keyword,district,type,sex,salary_time,order,nowCity);
	});

	$(".Gaddresses").on('tap','a',function(){
		$(".Gaddresses a").removeClass('active')
		$(this).addClass('active');
		//$("#alladdress").removeClass('active');
		var text = $(this).text();
		district = $(this).attr('data-district');
		if(district == ''){
			$("#Address").text('地区');
		} else {
			$("#Address").text(text);
		}
		$(".selectbox").hide();
		$(".selections").removeClass('active');
		Selection(keyword,district,type,sex,salary_time,order,nowCity);
	});

	$(".Gtypes a").on('tap',function(){
		$(".Gtypes a").removeClass('active')
		$(this).addClass('active');
		//$("#alltype").removeClass('active');
		var text = $(this).text();
		type = $(this).attr('data-type');
		if(type == ''){
			$("#Type").text('类型');
		} else {
			$("#Type").text(text);
		}
		$(".selectbox").hide();
		$(".selections").removeClass('active');
		Selection(keyword,district,type,sex,salary_time,order,nowCity);
	});

	$(".sexs a").on('tap',function(){
		$(".sexs a").removeClass('active')
		$(this).addClass('active');
		var text = $(this).text();
		sex = $(this).attr('data-sex');
		if(sex == ''){
			$("#Condition").text('性别');
		} else {
			$("#Condition").text(text);
		}
		$(".selectbox").hide();
		$(".selections").removeClass('active');
		Selection(keyword,district,type,sex,salary_time,order,nowCity);
	})

	// $(".salarys a").on('tap',function(){
	// 	$(".salarys a").removeClass('active')
	// 	$(this).addClass('active');
	// 	salary_time = $(this).attr('data-salary');
	// 	Selection(keyword,district,type,sex,salary_time,order,nowCity);
	// })

	$(".sorts a").on('tap',function(){
		$(".sorts a").removeClass('active')
		$(this).addClass('active');
		var text = $(this).text();
		$("#Sort").text(text);
		order = $(this).attr('data-order');
		$(".selectbox").hide();
		$(".selections").removeClass('active');
		if(order == 'juli'){
			Selection(keyword,district,type,sex,salary_time,order,nowCity,'asc');
		} else {
			Selection(keyword,district,type,sex,salary_time,order,nowCity);
		}
	});

	// $('.getcaptcha').on('tap',function(){
	// 	var mobile = $("#telphone").val();
	// 	if(mobile.length == ''){
	//         layer.msg('请填写手机号。');
	//         return false;
	//     }
	// 	if(mobile.length != 11){
	//         layer.msg('手机号长度不正确。');
	//         return false;
	//     }
	//     if(!checkMobile(mobile)){
	//     	layer.msg('请输入正确的手机号。');
 //        	return false;
 //        }

 //        $(this).attr('disabled','disabled');
 //        $.get('/job/getphonecode',{'mobile':mobile},function(data){
	// 		if(data.error_code == '0'){
	// 			mobileMsg();
	// 		} else {
	// 			layer.msg(data.reason);
	// 		}
	// 	},'json');
	// });

	// $("#TelBind").on('tap',function(){
	// 	var mobile = $("#telphone").val();
	// 	if(mobile.length == ''){
	//         layer.msg('请填写手机号。');
	//         return false;
	//     }
	// 	if(mobile.length != 11){
	//         layer.msg('手机号长度不正确。');
	//         return false;
	//     }
	//     if(!checkMobile(mobile)){
	//     	layer.msg('请输入正确的手机号。');
 //        	return false;
 //        }

	// 	var captcha = $("#captcha").val();
	// 	if(captcha.length == ''){
	//         layer.msg('请填写验证码。');
	//         return false;
	//     }

	//     $(this).attr('disabled','disabled');
	//     $.get('/job/edituserinfo',{'mobile':mobile,'vcode':captcha},function(data){
	// 		if(data.error_code == '0'){
	// 			layer.msg('绑定成功！');
	// 			layer.close(indexA);
	// 		} else {
	// 			layer.msg(data.reason);
	// 		}
	// 	},'json');
	// });

	

</script>


{% endblock %}
{% block footer %}
       
{% endblock %}