{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 我的兼职{% endblock %}

{% block content %}
<style type="text/css">
	#Jobs .lists {
		margin-bottom: 10px;
	}
	.mui-segmented-control {
		font-size:1.4rem;
		margin-top:-1rem;
		border-bottom: 1px solid #cbcbcb !important;
		background: #fff;
	}
	.mui-segmented-control .mui-control-item {
		line-height: 3rem;
		color:#8e8e8e;
	}
	.mui-segmented-control.mui-segmented-control-inverted .mui-control-item.mui-active {
		color: #f07527;
    	border-bottom: 2px solid #f07527;
	}
	
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">我的兼职</h1>
</header>

<div class="mui-content">
	<div id="usertop">
		<div class="userinfo clearfix">
			<div class="userimg left">
				<img src="{{ data['userinfo']['headimgurl'] }}" class="auto-center">
			</div>
			<div class="info">
				<div class="name">{{ data['userinfo']['nickname'] }}</div>
				<div class="else"><span class="score">4.9</span>52单</div>
			</div>
			<button id="Sign">签到</button>
		</div>
	</div>
	<div id="segmentedControl" class="mui-segmented-control mui-segmented-control-inverted mui-segmented-control-primary">
		<a href="#item1" class="mui-control-item mui-active">已报名</a>
		<a href="#item2" class="mui-control-item">已录用</a>
		<a href="#item3" class="mui-control-item">已拒绝</a>
	</div>
	<div id="Jobs">
		<div id="item1" class="mui-control-content mui-active">
			<ul class="mui-table-view joblist">
				{% for key, item in data['apply'] %}
					<li class="mui-table-view-cell lists" idvalue="{{ item['id'] }}">
						<a href="/job/detail?jobid={{ item['job_id'] }}">
							<h4>{{ item['joinfo']['title'] }}</h4>
							<div><span class="place">{{ item['joinfo']['district'] }}</span><span class="time">{{ item['joinfo']['start_date'] }} - {{ item['joinfo']['end_date'] }}</span></div>
							<div><span class="price">{{ item['joinfo']['salary'] }}元/{{ item['joinfo']['salary_type'] }}</span><span class="pricetype">{{ item['joinfo']['salary_time'] }}</span></div>
						</a>
						{% if item['type'] == 'Wait' %}
							<span class="stat">已报名</span>
						{% elseif item['type'] == 'N' %}
							<span class="stat">已拒绝</span>
						{% elseif item['type'] == 'Y' %}
							<span class="stat">已录用</span>
						{% endif %}
						{% if item['type'] == 'Wait' %}
							<div class="controls">
								<a href='javascript:void(0)' class="canclejob" data-stat="cancle" data-id="{{ item['id'] }}">取消报名</a>
							</div>
						{% elseif item['type'] == 'N' %}

						{% elseif item['type'] == 'Y' %}
							<div class="controls">
								<a href='javascript:void(0)' class="canclejob" data-stat="cancle" data-id="{{ item['id'] }}">取消报名</a>
								<a href="tel:{{ item['joinfo']['phone'] }}" data-stat="contact">联系督导</a>
							</div>
						{% endif %}
					</li>
				{% endfor %}
			</ul>
		</div>
		<div id="item2" class="mui-control-content">
			<ul class="mui-table-view joblist">
				{% for key, item in data['apply'] %}
				{% if item['type'] == 'Y' %}
					<li class="mui-table-view-cell lists" idvalue="{{ item['id'] }}">
						<a href="/job/detail?jobid={{ item['job_id'] }}">
							<h4>{{ item['joinfo']['title'] }}</h4>
							<div><span class="place">{{ item['joinfo']['district'] }}</span><span class="time">{{ item['joinfo']['start_date'] }} - {{ item['joinfo']['end_date'] }}</span></div>
							<div><span class="price">{{ item['joinfo']['salary'] }}元/{{ item['joinfo']['salary_type'] }}</span><span class="pricetype">{{ item['joinfo']['salary_time'] }}</span></div>
						</a>
						<span class="stat">已录用</span>
						<div class="controls">
							<a href='javascript:void(0)' class="canclejob" data-stat="cancle" data-id="{{ item['id'] }}">取消报名</a>
							<a href="tel:{{ item['joinfo']['phone'] }}" data-stat="contact">联系督导</a>
						</div>
					</li>
				{% endif %}
				{% endfor %}
			</ul>
		</div>
		<div id="item3" class="mui-control-content">
			<ul class="mui-table-view joblist">
				{% for key, item in data['apply'] %}
				{% if item['type'] == 'N' %}
					<li class="mui-table-view-cell lists" idvalue="{{ item['id'] }}">
						<a href="/job/detail?jobid={{ item['job_id'] }}">
							<h4>{{ item['joinfo']['title'] }}</h4>
							<div><span class="place">{{ item['joinfo']['district'] }}</span><span class="time">{{ item['joinfo']['start_date'] }} - {{ item['joinfo']['end_date'] }}</span></div>
							<div><span class="price">{{ item['joinfo']['salary'] }}元/{{ item['joinfo']['salary_type'] }}</span><span class="pricetype">{{ item['joinfo']['salary_time'] }}</span></div>
						</a>
						<span class="stat">已拒绝</span>
					</li>
				{% endif %}
				{% endfor %}
			</ul>
		</div>
	</div>
</div>
<script type="text/javascript">

	$('.canclejob').on('tap',function(){
		var _this = $(this);
		var dom = _this.parents('li').find('.stat');
		var id = _this.attr('data-id');
		var btnArray = ['取消', '确定'];
	    mui.confirm("您确定要取消该报名？", '确认取消报名', btnArray, function(e) {
			if (e.index == 1) {
				//$(".citys a[data-code='"+codA+"']").click();
				$.get('/job/delapply',{'applyid':id},function(data){
					if(data.error_code == '0'){
						layer.msg("已取消报名。");
						_this.parent().remove();
						dom.html('已取消');
					} else {
						layer.msg(data.reason);
					}
				},'json')
			} else {
				
			}
		})
		
	});

</script>
{% endblock %}
{% block footer %}
       
{% endblock %}