{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 我的简历{% endblock %}

{% block content %}
<style type="text/css">
	
	
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">我的简历</h1>
	<a href="/job/user" class="mui-pull-right"><span class="mui-icon mui-icon-contact"></span></a>
</header>

<div class="mui-content">
	<div id="usertop">
		<div class="userinfo clearfix">
			<div class="userimg left">
				<img src="{{ data['userinfo']['headimgurl'] }}" class="auto-center">
			</div>
			<div class="info">
				<div class="name">{{ data['userinfo']['nickname'] }}</div>
				<div class="else"><span class="score">4.9</span>52单</div>
			</div>
			<button id="Sign">签到</button>
		</div>
	</div>
	<div id="Resume">
		<div class="resu romA">
			<input type="hidden" value="{{ data['userinfo']['phone'] }}">
			<div class="mui-input-row">
				<label>姓名</label>
				<input type="text" placeholder="请输入您的真实姓名" id="userName" value="{{ data['userinfo']['real_name'] }}">
			</div>
			<div class="mui-input-row">
				<label>性别</label>
				<input type="text" placeholder="请选择您的性别" id="changeUserSex" value="{{ data['userinfo']['sex'] }}" readonly="readonly">
			</div>
			<div class="mui-input-row">
				<label>生日</label>
				<input type="text" data-options='{"type":"date","beginYear":1960,"endYear":2016}' value="{{ data['userinfo']['birth'] }}" id="userBirthday" placeholder="请选择您的生日" readonly="readonly">
			</div>
			<div class="mui-input-row">
				<label>身份</label>
				<input type="text" placeholder="请输入您的身份" value="{{ data['userinfo']['identity'] }}" id="userIdentity">
			</div>
			<div class="mui-input-row">
				<label>学历</label>
				<input type="text" placeholder="请选择您的学历" id="userDegree" value="{{ data['userinfo']['education'] }}" readonly="readonly">
			</div>
		</div>
		<div class="resu romB">
			<div class="mui-input-row">
				<label>工作经验</label>
				<input type="text" placeholder="请选择工作经验" id="userJobyear" value="{{ data['userinfo']['experience'] }}" readonly="readonly">
			</div>
			<div class="mui-input-row">
				<label>工作领域</label>
				<input type="text" placeholder="请选择工作领域" id="userJobfield" value="{{ data['userinfo']['workarea'] }}" readonly="readonly">
			</div>
		</div>
	</div>
</div>
<button id="Push" class="footbtn">保存简历</button>
<script type="text/javascript">

	$("#Push").on('tap',function(){

		var real_name = $("#userName").val();
		if(real_name.length == ''){
	        layer.msg('请填写姓名。');
	        return false;
	    }
	    if(!checkName(real_name)){
	    	layer.msg('请填写真实姓名。');
        	return false;
        }

        var sex = $("#changeUserSex").val();
        if(sex.length == ''){
	        layer.msg('请选择性别。');
	        return false;
	    }

	    var birth = $("#userBirthday").val();
        if(birth.length == ''){
	        layer.msg('请选择生日。');
	        return false;
	    }

	    var birth = $("#userBirthday").val();
        if(birth.length == ''){
	        layer.msg('请选择生日。');
	        return false;
	    }

	    var identity = $("#userIdentity").val();
        if(identity.length == ''){
	        layer.msg('请填写身份。');
	        return false;
	    }

	    var education = $("#userDegree").val();
        if(education.length == ''){
	        layer.msg('请选择学历。');
	        return false;
	    }

	    var experience = $("#userJobyear").val();
        if(experience.length == ''){
	        layer.msg('请选择工作经验。');
	        return false;
	    }

	    var workarea = $("#userJobfield").val();
        if(workarea.length == ''){
	        layer.msg('请选择工作领域。');
	        return false;
	    }

	    indexload = layer.load(2, {
		  shade: [0.4,'#000'] //0.1透明度的白色背景
		});

	    $.get("/job/editresume",{
	    	"real_name":real_name,
	    	"sex":sex,
	    	"birth":birth,
	    	"identity":identity,
	    	"education":education,
	    	"experience":experience,
	    	"workarea":workarea
	    },function(data){
	    	if(data.error_code == '0'){
				layer.msg('简历提交成功！');
				layer.close(indexload);
				setTimeout("window.location.href = '/job/user'",2000);
			} else {
				layer.close(indexload);
				layer.msg(data.reason);
			}
	    },'json')

	});
	

</script>
{% endblock %}
{% block footer %}
       
{% endblock %}