{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 账号设置{% endblock %}

{% block content %}
<style type="text/css">
	
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">账号设置</h1>
</header>

<div class="mui-content">
	<a href="/job/logout" class="footbtn" id="Logout">退出登录</a>
</div>

{% endblock %}
{% block footer %}
       
{% endblock %}