{% extends "common/mobile-index.phtml" %}
{% block title  %}兼职头条 - 报名成功{% endblock %}

{% block content %}
<style type="text/css">
	body,html,.mui-content{
		background: #fff;
	}
	
</style>

<header class="mui-bar mui-bar-nav">
	<a class="mui-action-back mui-icon mui-icon-left-nav mui-pull-left"></a>
	<h1 class="mui-title">报名成功</h1>
</header>

<div class="mui-content">
	<div class="signdone">
		<h2>报名成功！</h2>
		<p>请长按二维码添加督导微信，或拨打电话联系督导。</p>
		<img class="QRcode" src="{{ data['jobinfo']['wxcode_img'] }}">
		<!-- <button class="footbtn">拨打电话{{ data['jobinfo']['phone'] }}</button> -->
		<a class="footbtn" href="tel:{{ data['jobinfo']['phone'] }}">拨打电话</a>
	</div>
	<div>
		<a id="SignAD" href="javascript:void(0)"></a>
		<a href="javascript:void(0)" class="footbtn" id="gojob">继续找兼职</a>
	</div>
</div>

<script type="text/javascript">

	$("#gojob").on('tap',function(){
		var city = $.cookie('city');
		window.location.href = '/job/index?city='+city;
	});
	
</script>

{% endblock %}
{% block footer %}
       
{% endblock %}